apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secrets-common-to-ci-ns
  annotations:
    policies.kyverno.io/title: Sync CI Secrets
    policies.kyverno.io/category: SRE
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Copy common secrets to all CI namespaces
spec:
  rules:
    {{- range $secret := .Values.commonSecretsListToCI }}

    - name: {{ (print "common-secrets-" $secret.name) | trunc 63 | trimSuffix "-" }}
      preconditions:
        all:
          - key: "{{`{{`}} request.namespace {{`}}`}}"
            operator: Equals
            value: "ci-*"
      match:
        all:
          - resources:
              kinds:
                - Namespace                  
      generate:
        apiVersion: v1
        kind: Secret
        name: "{{ $secret.name }}"
        namespace: "{{`{{`}}request.object.metadata.name{{`}}`}}"
        synchronize: true
        clone:
          namespace: "{{ $secret.namespace }}"
          name: "{{ $secret.name }}"
    {{ end }}