---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secrets-from-ci-ns
  annotations:
    policies.kyverno.io/title: Sync CI Secrets
    policies.kyverno.io/category: SRE
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Copy secrets from ci-namespace to new rancher namespace
spec:
  rules:
    {{- range $index, $project := .Values.projects }}
    - name: sync-secrets-{{ $project.projectName | lower }}
      match:
        any:
          - resources:
              kinds:
                - Namespace
              # operations:
              #   - CREATE
              annotations:
                field.cattle.io/projectId: {{ $project.projectId | quote }}
      generate:
        namespace: "{{`{{`}}request.object.metadata.name{{`}}`}}"
        synchronize: true
        cloneList:
          namespace: "ci-{{ $project.projectName | lower }}"
          kinds:
            - v1/Secret
    {{- end }}