apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-sre-secrets-from-startups
  annotations:
    policies.kyverno.io/title: Sync CI Secrets
    policies.kyverno.io/category: SRE
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Copy secrets from ci-namespace to an SRE managed namespace
spec:
  rules:
    {{- range $index, $project := .Values.projects }}
    - name: {{ (print "sync-sre-secrets-from-startups-" $project.projectName | lower) | trunc 63 | trimSuffix "-" }}
      preconditions:
        all:
          - key: "{{`{{`}} request.object.metadata.annotations.\"field.cattle.io/projectId\" || '' {{`}}`}}"
            operator: Equals
            value: ""
      match:
        all:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  sre.socialgouv.github.io/startup: {{ $project.projectName | quote }}
      generate:
        namespace: "{{`{{`}}request.object.metadata.name{{`}}`}}"
        synchronize: true
        # https://github.com/kyverno/kyverno/issues/8025
        cloneList:
          namespace: "ci-{{ $project.projectName | lower }}"
          kinds:
            - v1/Secret
    {{- end }}
