apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-sre-secrets
  annotations:
    policies.kyverno.io/title: Sync CI Secrets
    policies.kyverno.io/category: SRE
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Copy SRE secrets to SRE managed namespaces that need it
spec:
  rules:
    {{- range $secretCloneDef := .Values.sreSecretsList }}

    {{ $from := "" }}
    {{ $to := "" }}
    {{- if kindIs "string" $secretCloneDef  }}
    {{ $from = $secretCloneDef }}
    {{ $to = $secretCloneDef }}
    {{- else }}
    {{ $from = $secretCloneDef.from }}
    {{ $to = $secretCloneDef.to }}
    {{ end }}

    - name: {{ (print "sync-sre-secrets-from-sre-" $from) | trunc 63 | trimSuffix "-" }}
      preconditions:
        all:
          - key: "{{`{{`}} request.object.metadata.annotations.\"field.cattle.io/projectId\" || '' {{`}}`}}"
            operator: Equals
            value: ""
      match:
        all:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  secrets.sre.socialgouv.github.io/{{ $to }}: "{{ $to }}"
      generate:
        apiVersion: v1
        kind: Secret
        name: "{{ $to }}"
        namespace: "{{`{{`}}request.object.metadata.name{{`}}`}}"
        synchronize: true
        clone:
          namespace: "sre-secrets"
          ## https://github.com/kyverno/kyverno/issues/8025
          # name: "{{`{{`}} request.object.metadata.labels.\"secrets.sre.socialgouv.github.io/{{ $from }}\" {{`}}`}}"
          name: "{{ $from }}"
    {{ end }}