apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: vao
  name: cron-anonymizer
spec:
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: 0 * * * *
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          securityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsGroup: 1000
          containers:
            - name: anonymizer
              image: ghcr.io/socialgouv/docker/greenmask:1.1.3
              resources:
                requests:
                  cpu: 1000m
                  memory: 1Gi
                limits:
                  cpu: 2000m
                  memory: 3Gi
              envFrom:
                - secretRef:
                    name: pg-app
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: bucket_access_key
                      name: vao-prod-backups-access-key
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: bucket_secret_key
                      name: vao-prod-backups-access-key
                - name: AWS_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      key: bucket_name
                      name: vao-prod-backups-access-key
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      key: bucket_region
                      name: vao-prod-backups-access-key
                - name: AWS_ENDPOINT_URL
                  valueFrom:
                    secretKeyRef:
                      key: bucket_endpoint
                      name: vao-prod-backups-access-key
              volumeMounts:
                - name: workspace
                  mountPath: /workspace
              command:
                - sh
                - -c
                - |
                  cd /workspace/.anonymizer
                  ./anonymize-prod.sh
                  aws s3 cp --recursive /tmp/pg_dump/ s3://vao-prod-backups/anonymizer/pg_dumps/
          initContainers:
            - name: degit-repository
              image: ghcr.io/socialgouv/kontinuous/degit:v1.169.11
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  degit --disable-cache --verbose --mode=git https://github.com/SocialGouv/vao.git /workspace
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              volumeMounts:
                - name: workspace
                  mountPath: /workspace
          volumes:
            - name: workspace
              emptyDir: {}
