kuik:
  manager:
    replicas: 2
    pdb:
      create: true
      minAvailable: 1
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: kuik
            app.kubernetes.io/component: manager
    webhook:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kube-system
              - kyverno
              - openebs
              - cattle-system
              - cert-manager
              - kuik-system

harborRegistry: harbor.fabrique.social.gouv.fr
harborDockerHubProxyPath: /hub
