apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    component: metabase-matomo-sync
    application: metabase-matomo-sync
  name: metabase-matomo-sync
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: metabase-matomo-sync
            application: metabase-matomo-sync
          name: metabase-matomo-sync
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            runAsNonRoot: true
          restartPolicy: OnFailure
          containers:
            - name: metabase-matomo-sync-container
              image: node:14-alpine
              resources:
                requests:
                  cpu: "1"
                  memory: 512Mi
                limits:
                  cpu: "1"
                  memory: 512Mi
              securityContext:
                allowPrivilegeEscalation: false
              command:
                - sh
                - -c
                - npx @socialgouv/matomo-postgres
              envFrom:
                - secretRef:
                    name: matomo-key
              env:
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: managed-db-metabase
                      key: PGURL
                - name: STARTDATE
                  value: "2019-01-01"
                - name: DEBUG
                  value: "*"
                - name: DESTINATION_TABLE
                  value: "matomo"
                - name: MATOMO_SITE
                  value: "22"
                - name: MATOMO_URL
                  value: "https://matomo.fabrique.social.gouv.fr"
