apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: metabase
  namespace: startup-ozensemble--metabase-prod
spec:
  encryptedData:
    MB_ENCRYPTION_SECRET_KEY: AgBwbUoaMhvFVMA2Bub7TRJJN6z3pEyNtkPYqC4FImipK833K7EvKL0LMOuUZ6MQymuV34B3sJlLSxfXCgqjvHS23NN18+mZwScnWP9NyLfPmnRfcXEWHI4o3G1oCXNR5W8XSESLF+G1bqDqEfpKnyRCAR00Gfiel+V2cUSnv5rkA8APWTo7hwNI01RXsFKD9nsbFEnxzO/cRCGuBWymYIRFkGFX0qLCXR7D5oThLkGQaBmku0Y+ZJ/zdmUh/lWMhRjo60r4B9DzXurU1XEucA6MrrZcB8GyWk/+rgcINHT9WN1c/lVkc7kD9/kMoHnTOZ6Oe4dGvNEf/3p5+AGOpdXKHWsvj1dHMYcv7WTKVP4hLzZOsoqdqLlNeRrkrI2vArJIgROHHUIVeh/oTzv1aguIh0SxOk751JG0vI2UdIMw2MvneI10asua1EZoeYC7bL4ih1xgxJWBbkOb1hQr5KZ4ZLJ5zROWB2hlKsKX0ZlE1Kon0FWogVwh24SKAH0qz+rVvDpFEr2TVdAuWRqXRDtwe08wG2ezRtc7NU/pVxzSEsFslTwfSdOs9EgGGVzxSbhXiaKI9kIYgtRpSTHtUASQlpVCV7QG1ONK8aJoK0bwoBQALT6QXB1sBV1egdYnnmmBovpSkn6UMSTQfqyQppyvrjHkiz+vLhnBZbpcWOJ1YFMDuA1pv1OVLiR4vt78PgF4kA1R2M05t/T3wS939ZcI889hhT8f7Qa1ESu112d5ptwPxJBpvXaZi6FM6f+5fFxe2A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: metabase
    type: Opaque

