apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ns
spec:
  policyTypes:
    - Ingress
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: domifa-preprod
