apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: {{ include "common.names.fullname" . }}
    application: {{ include "common.names.fullname" . }}
  name: {{ include "common.names.fullname" . }}
data:
  HOST_PORT: "8080"
