apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: {{ include "common.names.fullname" . }}
    application: {{ include "common.names.fullname" . }}
    {{ if .Values.labels }}
    {{ range $key, $val := .Values.labels }}
    "{{ $key }}": {{ $val | quote }}
    {{ end }}
    {{ end }}
  name: {{ include "common.names.fullname" . }}
  annotations:
    {{ if .Values.annotations }}
    {{ range $key, $val := .Values.annotations }}
    "{{ $key }}": {{ $val | quote }}
    {{ end }}
    {{ end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      component: {{ include "common.names.fullname" . }}
  template:
    metadata:
      labels:
        component: {{ include "common.names.fullname" . }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - image: "{{ .Values.image }}"
          name: app
          env:
            - name: ALLOWED_HOSTS
              value: "{{ .Values.ingress.host }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-app
                  key: uri
            - name: HOST_PORT
              value: "8080"
            {{- if gt (len .Values.env) 0 }}
            {{- tpl (.Values.env | toYaml) . | nindent 12 }}
            {{- end }}
          {{- if gt (len .Values.envFrom) 0 }}
          envFrom:
            {{- tpl (.Values.envFrom | toYaml) . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 3000
              name: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
