apiVersion: v2
name: metabase
version: 0.0.0
dependencies:
  - name: final-appset
    repository: file://./charts/final-appset
    version: 0.0.0
  - name: metabase
    repository: file://./charts/metabase
    version: 0.0.0
    condition: metabase.enabled
