metabase:
  enabled: true
  fullnameOverride: metabase
  cnpg-cluster:
    persistence:
      size: 16Gi
    backup:
      enabled: true
      barmanObjectStore:
        destinationPath: s3://ozensemble-prod-backups/metabase-prod-2024-02-26
        endpointURL: https://s3.gra.io.cloud.ovh.net
        s3Credentials:
          accessKeyId:
            name: &s3secretName ozensemble-prod-backups-access-key
          region:
            name: *s3secretName
          secretAccessKey:
            name: *s3secretName
