existingSecret: "env"
env:
  OBLIK_DEFAULT_CRON: "0 0,2,4 * * *" # UTC
  OBLIK_DEFAULT_CRON_ADD_RANDOM_MAX: 60m

  OBLIK_DEFAULT_LIMIT_CPU_CALCULATOR_VALUE: "1.5"
  OBLIK_DEFAULT_LIMIT_MEMORY_CALCULATOR_VALUE: "1"
  OBLIK_DEFAULT_MIN_REQUEST_CPU: 100m
  OBLIK_DEFAULT_MIN_REQUEST_MEMORY: 250Mi
  OBLIK_DEFAULT_MAX_REQUEST_CPU: "8"
  OBLIK_DEFAULT_MAX_REQUEST_MEMORY: 20Gi

  OBLIK_DEFAULT_UNPROVIDED_APPLY_DEFAULT_REQUEST_CPU: 100m
  OBLIK_DEFAULT_UNPROVIDED_APPLY_DEFAULT_REQUEST_MEMORY: 250Mi

  OBLIK_DEFAULT_WEBHOOK_ENABLED: "false" # temp

annotations:
  reloader.stakater.com/auto: "true"

image:
  tag: v0.1.7