---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cdtn-es-file-realm
  namespace: startup-cdtn--elasticsearch-dev
spec:
  encryptedData:
    users: AgBYQO2EG84eJGES3OgxC7/hKBvEUek6gXG5Ldv8Os657Uw9ya/EibMCI6LiReIAlWPhvsN0OrJjDIX85R+xOmUbzAhGs3s8un1YnSWZu5iXvMzvug200+kGiA/uM55VCR0njLZXeAsaPI0P/0Gykwph6Ehi7vV56DJtt2mRvh9ZN9gfVLDvU7zQzgUb3fjX7Q10BHyJTV5UaWPGSzYtK4lJI+gjdsqkGvVrGyhDiXwbc+M655sVdpDw9L+qn37UoQnFLcr+L2Cw0o191BkDdt8SlMKq2MTgQjO8mYjppOv8HXq7IvfTh/CAXIjNwLBZDYVY4IqPsV+KWoMwnqnLOXBTG8l00zw1CLaTD2bLGEZu+swc2QCmd0n16W5Ea44vHQGiEsYZ1VQN1xplgYwX5MAgaR9qLyQtmIvZKVfD2m9p88KvKDbgtcQGtZPa64+2mODPRPdWIMkxVgIEMNIruG4XMbrno0BI6uZtoz0AaRsKIKQkj4zPe3D13CiunSPqQCDaRmygG5/k4t6JUSTJ30Jaqbm4TF94KjKBhoQ0lCgwr2/A4/VYx2H/0Q64TeqNw3hvpQm+TVsmoqCKjsid6LvQ6jGajLEVZ/TznmX6bsroHL/c/GhO9UJddjJ4daOPpDtAr056t+HiIfnYDqZH1rGyJmWvDbOn8Cd/JjCh0HePZMqj7RAr7kXcAvB8rHIhUGKtp06k3w3fBSGe/gF9siD7O+SyYqFp7Buy1sePhAjMMl6pfTCDPGTayvro0Ojadwr/hdYccpEI4UGTqmlbF/s/Vn2Cjfv9iQ==
    users_roles: AgBlIylFAMtHH3F2eEmcEJdh8oDniAYGn3Oy43LHOGKh+Itj83a5hVstyX46gkjSHLuS9l6HQ/BTzLS7jdpBfRn5oFIUfwluT7WvP8MEyCIU3APYmXKfx46tSq136HfXgF+Qds6rkg9Gch1cNUnJAtiiIpX39RNZ7Sise6yXppsEgHIHvMNn+lGEZph/wAjts5sOe4R0iPJpth1ref35a6cskSlIyoFeqrsdnCC2s1S13uyPSM//FgaH6RRpWRV4fhJuITOtKUhkt/w42SOMHsdQdERBLKTmnZg77ygm+RHxpWPPWxCUPDrec9M1VJw1nS4Snoa23i6KCJUGIVCkr7WaTmlCprwFjJmKu+8Ps5WXSwOdF3vUWAMHhIu+plLBbG27EEsx40eRcf3eL6cd6F8fHpXQwZAzuzuwx+mmMN1bK8O0zA7q0Xc5xH03OjcUbwkdkkPNVLHhdk0zO5qBP17XRAAhCjmbExzGSiWhLEWFNmam7ltArAMc8WedyCAARNPotgmaOVDtspGmlN9ReP77CnXFc1Cm+9k0+m6EaiPVOCXQDv67m1oJAjSDYdkUrexAAuviZV4zj7OMHcBTpd56NoMkfRbsu24TBJvf61DVD4Orzb/gwjIVrn476gAfRh9BlUnVep5ADyQ4pdnB7w7jOcpSPp0QcLNyZQgvQVRvGJBNFpL2FdebwWLoWjOPiCAGOUJh6sSlnNGU0VcxHwV8An1AtA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cdtn-es-file-realm
      namespace: startup-cdtn--elasticsearch-dev
