apiVersion: v1
kind: Service
metadata:
  name: appset-rancher-projects-plugin
  labels:
    app: appset-rancher-projects-plugin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: appset-rancher-projects-plugin
  type: ClusterIP