metabase:
  enabled: true
  fullnameOverride: metabase
  cnpg-cluster:
    backup:
      enabled: true
      barmanObjectStore:
        destinationPath: s3://carte-jeune-engage-prod-backups/metabase-ovh
        endpointURL: https://s3.gra.io.cloud.ovh.net
        s3Credentials:
          accessKeyId:
            name: &s3secretName carte-jeune-engage-prod-backups-access-key
          region:
            name: *s3secretName
          secretAccessKey:
            name: *s3secretName

metabase-matomo-sync:
  enabled: true
  matomoSiteId: 103
  fullnameOverride: metabase-matomo-sync
  cnpg-cluster:
    persistence:
      size: 20Gi
    backup:
      enabled: true
      barmanObjectStore:
        destinationPath: s3://carte-jeune-engage-prod-backups/metabase-matomo-sync-ovh
        endpointURL: https://s3.gra.io.cloud.ovh.net
        s3Credentials:
          accessKeyId:
            name: &s3secretName carte-jeune-engage-prod-backups-access-key
          region:
            name: *s3secretName
          secretAccessKey:
            name: *s3secretName

metabase-matomo-sync-preprod:
  enabled: true
  matomoSiteId: 112
  fullnameOverride: metabase-matomo-sync-preprod
  pgdatabase:
    secretName: metabase-matomo-sync-app
  destinationTable: matomo_preprod
  cnpg-cluster:
    enabled: false
