apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
spec:
  project: default
  destination:
    name: ovh-dev
    namespace: arc-runners
  source:
    path: arc-runners
    repoURL: https://github.com/SocialGouv/infra-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  resource:
    exclusions:
      - apiVersion: actions.github.com/v1alpha1
        kind: AutoscalingListener
        namespace: arc-systems
