apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
spec:
  project: default
  destination:
    name: ovh-dev
    namespace: arc-runners
  source:
    path: arc-runners
    repoURL: https://github.com/SocialGouv/infra-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  resourceExclusions:
    - apiGroups:
        - actions.github.com
      kinds:
        - AutoscalingListener
      clusters:
        - "*"
    - apiGroups:
        - ""
      kinds:
        - ServiceAccount
      clusters:
        - "*"
      # Only exclude ServiceAccounts with specific patterns
      nameRegex: ".*-gha-rs-no-permission$"
    - apiGroups:
        - rbac.authorization.k8s.io
      kinds:
        - Role
        - RoleBinding
      clusters:
        - "*"
      # Only exclude RBAC resources created by the listener
      nameRegex: ".*-listener$"