apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
spec:
  project: default
  destination:
    name: ovh-dev
    namespace: arc-runners
  source:
    path: arc-runners
    repoURL: https://github.com/SocialGouv/infra-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: actions.github.com
    kind: AutoscalingListener
    jqPathExpressions:
      - '.' # Ignore the entire AutoscalingListener resource completely
  - group: rbac.authorization.k8s.io
    kind: Role
    jqPathExpressions:
      - 'select(.metadata.labels["actions.github.com/scale-set-name"] == "arc-runners")'
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    jqPathExpressions:
      - 'select(.metadata.labels["actions.github.com/scale-set-name"] == "arc-runners")'

