apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
spec:
  project: default
  destination:
    name: ovh-dev
    namespace: arc-runners
  source:
    path: arc-runners
    repoURL: https://github.com/SocialGouv/infra-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: actions.github.com
    kind: AutoscalingListener
    jqPathExpressions:
      - '.'
  - group: ""
    kind: ServiceAccount
    name: arc-runners-gha-rs-no-permission
    jqPathExpressions:
      - '.'
  - group: rbac.authorization.k8s.io
    kind: Role
    jqPathExpressions:
      - '.metadata.name | test("arc-runners-.*-listener")'
      - '.metadata.name == "arc-runners-gha-rs-manager"'
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    jqPathExpressions:
      - '.metadata.name | test("arc-runners-.*-listener")'
      - '.metadata.name == "arc-runners-gha-rs-manager"'
