apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
spec:
  project: default
  destination:
    name: ovh-dev
    namespace: arc-runners
  source:
    path: arc-runners
    repoURL: https://github.com/SocialGouv/infra-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  # Ignore resources created and managed by the ARC operator
  ignoreDifferences:
    # Ignore AutoscalingListener resources (managed by operator)
    - group: actions.github.com
      kind: AutoscalingListener
      jsonPointers:
        - /metadata/finalizers
        - /metadata/deletionTimestamp
        - /metadata/deletionGracePeriodSeconds
        - /metadata/resourceVersion
        - /metadata/generation
        - /spec
        - /status
    # Ignore ServiceAccount resources with cleanup finalizers
    - group: ""
      kind: ServiceAccount
      name: arc-runners-gha-rs-no-permission
      jsonPointers:
        - /metadata/finalizers
        - /metadata/deletionTimestamp
        - /metadata/deletionGracePeriodSeconds
        - /metadata/resourceVersion
    # Ignore RBAC resources created by the operator
    - group: rbac.authorization.k8s.io
      kind: Role
      nameRegex: "arc-runners-.*-listener"
      jsonPointers:
        - /metadata/labels
        - /metadata/resourceVersion
        - /rules
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      nameRegex: "arc-runners-.*-listener"
      jsonPointers:
        - /metadata/labels
        - /metadata/resourceVersion
        - /subjects
        - /roleRef