apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
spec:
  project: default
  destination:
    name: ovh-dev
    namespace: arc-runners
  source:
    path: arc-runners
    repoURL: https://github.com/SocialGouv/infra-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  # https://github.com/orgs/community/discussions/126862
  # was unable to make ignoreDifferences work
  