apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-systems
spec:
  project: default
  destination:
    name: ovh-dev
    namespace: arc-systems
  source:
    path: arc-systems
    repoURL: "git@github.com:SocialGouv/manifests.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
