apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2esdk-dev
spec:
  destination:
    name: ovh-dev
    namespace: e2esdk-dev
  project: default
  source:
    repoURL: git@github.com/SocialGouv/manifests.git
    targetRevision: master
    path: e2esdk-dev
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        application: sre
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
