apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator-ovh-prod
spec:
  project: default
  destination:
    name: ovh-prod
    namespace: elastic-system
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 3.2.0
    helm:
      releaseName: elastic-operator
      values: |
        installCRDs: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    # Uncomment if you want fully automated sync
    # automated:
    #   prune: true
    #   selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
