apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-image-keeper
spec:
  generators:
    - list:
        elements:
          - name: kube-image-keeper-dev
            cluster: ovh-dev
          # - name: kube-image-keeper-prod
          #   cluster: ovh-prod
  goTemplate: true
  template:
    metadata:
      name: "{{ .name }}"
      # annotations:
      # labels:
    spec:
      destination:
        name: "{{ .cluster }}"
        namespace: "kuik-system"
      project: default
      source:
        repoURL: https://github.com/SocialGouv/infra-apps.git
        targetRevision: master
        path: charts/kube-image-keeper
        helm:
          releaseName: kube-image-keeper
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        