apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: n8n
spec:
  generators:
    - list:
        elements:
          - name: n8n-prod
            cluster: ovh-prod
  goTemplate: true
  template:
    metadata:
      name: "{{ .name }}"
      # annotations:
      # labels:
    spec:
      destination:
        name: "{{ .cluster }}"
        namespace: "n8n"
      project: default
      source:
        repoURL: https://github.com/SocialGouv/infra-apps.git
        targetRevision: master
        path: "n8n"
        helm:
          releaseName: n8n
          valueFiles:
            - "values.yaml"
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            application: n8n
        syncOptions:
          - CreateNamespace=true
          #- Replace=true
        # automated: 
        #   prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
