apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: no-package-malware
spec:
  generators:
    - list:
        elements:
          - name: no-package-malware-prod
            namespace: no-package-malware
            cluster: ovh-prod
            instanceValuesFile: values.prod.yaml
          # - name: no-package-malware-preprod
          #   namespace: no-package-malware
          #   cluster: preprod
          #   instanceValuesFile: values.preprod.yaml
  goTemplate: true
  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
        notifications.argoproj.io/subscribe.mattermost: moojipgstjgsixs6mgycxpe5ua
      # labels:
    spec:
      destination:
        name: "{{ .cluster }}"
        namespace: "{{ .namespace }}"
      project: default
      source:
        repoURL: https://github.com/SocialGouv/infra-apps.git
        targetRevision: master
        path: "no-package-malware"
        helm:
          releaseName: no-package-malware
          valueFiles:
            - "values.yaml"
            - "{{ .instanceValuesFile }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          #- Replace=true
        automated: {}
        #   prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
