apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openebs-nfs
spec:
  generators:
    - list:
        elements:
          - name: openebs-nfs-ovh-dev
            namespace: openebs
            cluster: ovh-dev
          - name: openebs-nfs-ovh-prod
            namespace: openebs
            cluster: ovh-prod
  goTemplate: true
  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .
      # labels:
    spec:
      destination:
        name: "{{ .cluster }}"
        namespace: "{{ .namespace }}"
      project: default
      source:
        repoURL: https://github.com/SocialGouv/infra-apps.git
        targetRevision: master
        path: "openebs/nfs"
        helm:
          releaseName: openebs-nfs
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          #- Replace=true
        automated: null
        #   prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
