apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resources
spec:
  generators:
    - list:
        elements:
          - name: resources-dev
            cluster: ovh-dev
          - name: resources-prod
            cluster: ovh-prod
  goTemplate: true
  template:
    metadata:
      name: "{{ .name }}"
    spec:
      destination:
        name: "{{ .cluster }}"
      project: default
      source:
        repoURL: https://github.com/SocialGouv/infra-apps.git
        targetRevision: master
        path: "resources"
        helm:
          valueFiles:
            - "values.yaml"
            - "values.{{ .cluster }}.yaml"
      syncPolicy:
        syncOptions:
          - Force=true
          - Replace=true
        automated:
          prune: true
          selfHeal: false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
