apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-policies
spec:
  generators:
    - plugin:
        configMapRef:
          name: appset-rancher-projects-plugin

  goTemplate: true
  template:
    metadata:
      name: "secrets-policies-{{ .cluster }}"
      # labels:
    spec:
      destination:
        name: "{{ .cluster }}"
        namespace: "secrets-policies"
      project: default
      source:
        repoURL: git@github.com/SocialGouv/manifests.git
        targetRevision: master
        path: "secrets-policies"
        helm:
          releaseName: secrets-policies
          values: |
            projects: {{ toJson .projects }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          # selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
