apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secretgen
spec:
  generators:
    - list:
        elements:
          - name: secretgen-prod
            cluster: ovh-prod
          - name: secretgen-dev
            cluster: ovh-dev
  goTemplate: true
  template:
    metadata:
      name: "{{ .name }}"
    spec:
      destination:
        name: "{{ .cluster }}"
        namespace: "secretgen-controller"
      project: default
      source:
        repoURL: git@github.com/SocialGouv/infra-apps.git
        targetRevision: master
        path: "charts/secretgen"
        helm:
          releaseName: secretgen
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
