apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: token-bureau
spec:
  generators:
    - list:
        elements:
          - name: token-bureau-prod
            cluster: ovh-prod
  goTemplate: true
  template:
    metadata:
      name: "{{ .name }}"
      # annotations:
      # labels:
    spec:
      destination:
        name: "{{ .cluster }}"
        namespace: "token-bureau"
      project: default
      source:
        repoURL: https://github.com/SocialGouv/infra-apps.git
        targetRevision: master
        path: "token-bureau"
        helm:
          releaseName: token-bureau
          valueFiles:
            - "values.yaml"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          #- Replace=true
        # automated: 
        #   prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
