metabase:
  host: metabase-carte-jeune-engage.fabrique.social.gouv.fr
  ingress:
    annotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: true

final-appset:
  importSecretsFromStartup: true
  importSreSecretsList:
    - matomo-key
