env: []
envFrom: []

ingress:
  enabled: true
  host:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m

upstream:

additionalArgs: []
replicas: 1

image:
  name: quay.io/oauth2-proxy/oauth2-proxy
  tag: v7.4.0
