apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "infra-as-blueprint.name" . }}
  name: {{ include "infra-as-blueprint.fullname" . }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}