apiVersion: v2
name: sftp
version: 0.0.0
dependencies:
  - name: sftpgo
    version: 0.22.0
    # https://artifacthub.io/packages/helm/sagikazarmark/sftpgo
    repository: https://charts.sagikazarmark.dev
    condition: sftpgo.enabled
  - name: cnpg-cluster
    version: 1.30.7
    repository: https://socialgouv.github.io/helm-charts
    condition: cnpg-cluster.enabled
