cnpg-cluster:
  enabled: true
  labels:
    application: n8n
  fullnameOverride: pg-n8n
  minSyncReplicas: 1
  maxSyncReplicas: 1
  instances: 3
  priorityClassName: cnpg-high-priority-3
  resources:
    requests:
      memory: 2G
      cpu: 512m
    limits:
      memory: 2G
      cpu: 1024m
  monitoring:
    enablePodMonitor: true
  persistence:
    size: 8Gi

n8n:
  config:
    database:
      type: postgresdb
      postgresdb:
        host: pg-n8n-rw
        database: app
        user: app
        schema: public
    executions:
      pruneData: "true"
      pruneDataMaxAge: 1440 # in hours (2 months)

  extraEnvSecrets:
    DB_POSTGRESDB_PASSWORD:
      name: pg-n8n-app
      key: password
    N8N_ENCRYPTION_KEY:
      name: n8n-encryption-key
      key: encryption-key
    QUEUE_BULL_REDIS_PASSWORD:
      name: n8n-redis
      key: redis-password
  
  persistence:
    enabled: false
    type: dynamic
    storageClass: "openebs-nfs-hspeed"
    accessModes:
      - ReadWriteMany
    size: 10Gi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io: cluster-issuer
      kubernetes.io/tls-acme: "true"
    className: nginx
    hosts:
      - host: n8n.fabrique.social.gouv.fr
        paths: 
          - "/"
    tls:
      - secretName: n8n-cert
        hosts:
          - n8n.fabrique.social.gouv.fr
  
  # scale
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10

  scaling:
    enabled: true
    worker:
      count: 2
      concurrency: 2
    webhook:
      enabled: true
      count: 2
  
  redis:
    enabled: true