cnpg-cluster:
  enabled: true
  labels:
    application: n8n
  fullnameOverride: pg-n8n
  minSyncReplicas: 1
  maxSyncReplicas: 1
  instances: 3
  priorityClassName: cnpg-high-priority-3
  resources:
    requests:
      memory: 2G
      cpu: 512m
    limits:
      memory: 2G
      cpu: 1024m
  monitoring:
    enablePodMonitor: true
  persistence:
    size: 8Gi

n8n:
  config:
    database:
      type: postgresdb
      postgresdb:
        host: pg-n8n-rw
        database: app
        user: app
        schema: public
    executions:
      pruneData: "true"
      pruneDataMaxAge: 1440 # in hours (2 months)

  extraEnvSecrets:
    DB_POSTGRESDB_PASSWORD:
      name: pg-n8n-app
      key: password
