apiVersion: v2
name: cdtn-elasticsearch
version: 0.1.0

description: Elasticsearch cluster for cdtn managed by Elastic Cloud on Kubernetes (ECK)

dependencies:
  - name: final-appset
    repository: file://./charts/final-appset
    version: 0.0.0
