apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  namespace: les1000jours
spec:
  storageClassName: sc-classic-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
