{{- if eq .Values.cluster "ovh-dev" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iterion-llm
  namespace: iterion-preprod
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgCHIFMswHECHiMNQz5xdQuhcFWDiUMH/BPH8pzYYyl8SY+9dhrfsPmWwG2QMDYuSTUBnEQkfyAdIAc6pznDEJbkFL030kQ7O9SPfHEfiOSczWCfDNBcBjKPx8FO4dkqklinQ1LA/snjRVDS2X+W+yGwfjXcpzUt4GW6nYBH1o3doYpwwybs42NRxgqjDTsvIQeibdcX5ZPal99jQZUY3neDZWy3MCtZip1C1uqDga875P1GdUBw3jl2INfug9PMlNklx4KQMN2yyYtguOoZ0QgibyDT2NTimCHAI8P5AER5ZIL0VBTRaTEY+pxMvcgm7a0bJdSL4p+uufs7HLV2FNwHZokAq66wNxhRrbD9FuMuQ4RR7Cgj2irL32unE3pJY8W8ZMWPoYyXI9L/Ho+M64JSEjhdedOfLtQE+AGCdWnuMJwTAxlb6Z+Dmfm7ByVNPoiQrUzJVmwEXY2Uy20lCQsVabbE0soJr+4ROUdj6rxpZZ2vpJuWk407Kf5IeYegDV6Q6F3FNsRcMbPYHKGJNnHiFRI6srpgT6TPSkN8iE+yDcd4WP9icMnxYQ1FtMcc3BL+u0QZ1EnjCsXk17zGQKP0v9SN/RPRZuLUJ9RYEkFcv3Px89WyZcmEou3tPYSrF/mkcoVMMjFnPgrGDvaGmLMKrK4M1UZ9/31q0bEZRYmRvILkA+b2nup5eO6q1K0TmDg=
    OPENAI_API_KEY: AgCPID9adfIJBwU3y+M7ZxTi7RHlu8+vkjc9XOWxlRwfg0dU25h25P23DT7cFds5MtYHta2jD78dpTqnemp2YG9iGsGR+vrIF8blazInlxQJt3QrwDqawWHhjlbf6FpYjU5ViKBbfskMuIdNHfEsSRioP9RxptMr8UMDksDb9OSfow6NIuj2zYtQnqitnYVUQ7NlZrVZ6shlV32S52iReRPL34GSf0kOxj70XcYsjZk+4s4ckaMEBZ07BguE354pOJfniPx9PB7PCv8pwzszIzAXDTEEDCmE3v4OhFNndnis1B064ZOdx2q3EF2PM2H84SZy8RhvNVf4ZQS8x+6y8t7TyM/pCYLhnR+h/unW2srY8U1y0u9maIAM8B69hlrCxaG8jO1YmXPGiXDOteGsLPebVXtG0d//FEby2fkWw1XrS+mISEnIWzjPcwuWSzU9u+2zkJ2sFOno8V1fKcDBt4BmOphpHJHrWWPEdBy+NKkUoI16RtChk7cOd1t20gHYMeTEgzRCnGusToAh324NuEPVnQAQ5JlznzTFL8+vjReX4qOulBtmcVLF6uYCEU9jYXpgXP8IlrHfOJFSMbmu5YpU6xfsC2Rf3SO3PVGhKQ5SiH6gEy7OeK2lJhsbAIbiYBnpIL3CbnLn2aopeheGVBlUF7Yz6wH57SYmg4tTc4OoPrM8r4uXhqfCFC5vjMDNzh4=
  template:
    metadata:
      creationTimestamp: null
      name: iterion-llm
      namespace: iterion-preprod
    type: Opaque
{{- end }}
