---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: iterion-searxng
  namespace: iterion
spec:
  encryptedData:
    SEARXNG_SECRET: AgCzBHN1BdxC/QBbMGoxBaw6BBDOb20MnOOrSyKHbPUsCtsjMq3deU8/M3OiKlDxIU2+VK6m4NKOScjgiCSKXgZD9PK4upuDkZemIVwddmg7pAIZTlZwViO6a7+lXYGbqAa+qVNI6R8BaiW1loNn3sUNvl5pIW9rF5UtAVEzh0IEZ4VlSi8/lOOXS6un+YttCpcMHKFW/3v7ht0pyfP0CrPYnJ013ZhSHKcefWuSFBmW3RDmYdnaMu+qXFMcN6UXM6XGKVprLRQZEOCblAFAbOgj+CCM6Y00aKzgTzXtEP7fnpG4fOefkUx7Aq+qJsQAZL30DVIqzF+uH53fOVEuS/vfyDkXbP/nXCVCP5om7ScSqfOR+coVpNapryOTkv6E6/Bhstt5p2DWay2bCfl636yPYzlTBSmacId6mg/KQMCSrUcm2X4dRm2raEt+84Ke4PuPS5BK9TCvbacPqRb5LmRLGDx/Nno9DEXCxlUkwQreV8qyZO19v3IaRioYGF7mQDnFoXRlDHAKRB8/aO5k1njDI2vjwKs0q8MSUjPAxfr1z5vTXVRYQUwOzPMlkeQxnELKUmNlmpEw9TSNC3mkj8wjEf5xnz52JwckRBLNNYwo/gImoOYgAG0R9o2cPGiGdbnesBh7fhWIjNluhDW3KXswOxaTWmEnTKcC6d/T99qWzLWZvRDG6lPD88etzss6QKDT4PxwUKk5P+gwVQo7HoAxrq+DKEZ/omNULdYszbyzvtCjEva6RwuDnAXpETS5RLnMcuUT4GVYEFWwtHpvkGWo
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: iterion-searxng
      namespace: iterion
