{{- if eq .Values.cluster "ovh-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iterion-storage
  namespace: iterion
spec:
  encryptedData:
    ITERION_S3_ACCESS_KEY_ID: AgCGJ4VYksUPAFhqJonk6potaGnSqGt1XoBg+xZcGMUkMctARvX/JJs1H+0S6pjVfnziqykwbo9QZ46T36z2CVQwXngEctBBJQuQclGI9Qi74As9U+VzHYbqAJC+8Zb6v+hB3b9CcTu10PE44RE8OK46NT0QYa5tiBOeBoJFTJcOu5LYpLvMBE8l/Wzre5sARiAdtiGTj6zXE5Y/TU0o2UXTHw3w/sgfRu4t5xBNECxvcfteltyb61h+bDiT8JbhO+J4B1AiXq6G318RAajxqUWMtuI0p7jbQO2HsTrkzaoHgLNq44sX4N0ISX/VvbjXVQpbtb+YFNEdtPzeOJNLvIOhPC0og6+Cn/9hoxtb9thnyOsmNtt780CjIsRpQhODKZvJPjbc9CKMnjqFrxDL1fT3us5O7XpWdJelMYbRVAbnQMkT3gOP/BBahAW5FhGYfcWVvJYnw8ZdzoEFqs+qava8APiA+0S73JAelStlKyckNAIy9NmZQbxgg8IRaCs0mp0q6bABtNBO+4JcPED83nIeGnm8G/22Fo42f7+A2mIGyYvYerym6KIZDkEndoA+A/Y+THhj8TaMTY+FnelbZEmkm1bFuMca0p2cqkFfjXMfYd4YsJZIvur55Uc5e+rqJB4oBbrApmlPXVAqZJ3OkhIz/Zz9s0/5cR8I/JV4rRfYXkIc84zOjKTbyu33EsSFWzrGLV8yXbgF6u8rMbk=
    ITERION_S3_SECRET_ACCESS_KEY: AgCWVY1QuwakbR4+qiKBEYJ18ufvo8wIix8xtQzoSgG9xSsqL123mrDOyvaQ8lCs86aBLlUPNLif1r3+Zfd/yw8rzQSZD/ZCz2McHt78VVviPW6GalDnb9FbNOopsweAza2SULYiadxk7A+KCSunt6hIzKWqyDyRpoVrlb9v9Lvv4k3//D245TYvD2YMHMt27S2ju6ZHZ2LwPShalq5VY88FkpaRrXKCF0TMA5lJ4JP3BBPuuiz04hESKyFQQY5TERybIoWo2YZjdU00eDQ9cyRfbQVbGj1vDOA6hWlX8/cGvxu7J1mGCSG2JY5dPzX/JRgniITn05MUV2Av7mzAh2qmFyCvsbolgC/jb70rSEvhJ3PQtbGIS5uSLCjHYjxl4h4T+GmHyyStPdRXR0BKY94cOo8pLes9XEEmouaEa6n2PkPn1LmqT10WPkTd0Egdh2sFXn5Xua+sI8jm9r6Ye8h2Yhcn0VHXkehDWNz/tyP9gbw4qkQhHietUCpoPhWfk4kJCZXC3g9UcN5It8mG/RYxPuz8XgXZ6yPDpfv4An3x7ppK8gW7Pn3uMjqOgKT8ooCT1kIObuSOF+VbJ0dVPgmgr32B5z+u36t9TPvxmntuAIIaSmY2lUugQH0wsW8+PUJttHKTNE8ZYyZBtYgDEoREnwGsK0G97kEe3iTpaoK64SSIsygB+SzSWVIMB3q7HUKMmu97ls6i/TeLHN6uxV45IyQMguvd3EgbYdb8
  template:
    metadata:
      creationTimestamp: null
      name: iterion-storage
      namespace: iterion
{{- end }}
