{{- if eq .Values.cluster "ovh-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iterion-mongodb-creds
  namespace: iterion
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCdSJAPaaUvxD3jX6aeo1VJjJKEFl4TkFaklGhqzUQMy8cfEzBsh227K4X94MLtC4rxwoy0YG9RATvxP9ipkZB3x/dzvuCXpxUC5ue6NXfhoZWMAKRz6zNDHn0+yF5UnU8YEbiBPTb05AH+20qdtPJGxf4uDQ5m1RXW1DvUcToUlWtL1469ft28kwffGPXP5uAaYjYZ6xe5YfzAHoZtRSfa3gWSr4DR3f/3eJak5GdfFFVREew06JYOm6EsSpB586AA0rBkEX17k+VKM/Ueftmmrpx28LqUf4joHLxHeYIIyGvKL42YRF+3zymm0BSUDjpN11F6xPxgfdhvA6eFSGTd5rdUUrW0TdFFeYYnbN+GxA0df+tVcHNvOiJhAwAbgX+lceIjwKNlRuJYaEkFY6cwCtOBc7CFCKegdobJdg2WT7ARXLj9Dg3XQ6D5ct3z9wQ2r8p86Tum/5CTEWhGsBQJvKTxSoW/RIDlZ+aS+pGhiCMBraDTxb+EjKzTqWRjICHAfX80wC4DTLflopIHJGtJ+oGsBB+wB7rwz/jCbpxg9tGt8wcjR69sYZrKsRyjyXU+j4XB7z4p254xm4t058TKQVzILhvwJXQmSOHahtRYXZ4WTHJBSZTMsNlPx5Pbd2kRNGCIAjxz1Xp7JCTJyRmbzqFLSnrgBoiY2nXVEPUTfbAObcjoUuPLh959uO4VHcUz3a1A0hjxEzeR9Nz+wehJkEoeHTPqV5s2YET+
    MONGO_INITDB_ROOT_USERNAME: AgBPuh3IKzte9yvaA8ElHxy3QIFZrH3jId1YD26x5bCDKEur5qXjFzDk0RPB1hMGbYO05ZzdPeT6L4Ry9YMYmU2VVnUL0mv1YfrEpaVFYn3BEV8IXVk1ICeNJMrbVQrReL8tQU22HNhvtXoM64eEJyM1wCWFr4KrUF0i15wXoFfsFlmaD4+8jIGXGZJgfO40EsyYefTrprqqhJ5jgSNBflBSkxY19QpjJYr0jy1Y+8YD1a76ozoBT5YoMn0So+Flw9l2FSls9d5odTQOWWdr5dC4bqCmbgUYM2/tHraU4pDoWm9LPI4aetV8AUBlOpOFMumuzqP/DPAxbne43UDsohvog8ehyBcbFCdT1UdBwbJ1qie4wzSP4gatJWsEQUDRIaA2hv2fC3KP4Pp/3mSdTlvOHA60O48WD45Sw5+K4l1D/9qICL924e/CZHYQ3McI4F7JK9eFwT4PJwCZQYy6p28UPuk0JSX2aVejNvH3FU3MaCKZoaj7HYHPtwVsFKou68P7faUrFp4SgYDJw6+c1LawmEpArp0T2Ypv9tCYA19Fvd7eTHnFInsBXujDl/QokPc5m01zckL/WA8nsO1upCqKDEC9sxMU/obaHpF0H1iWeCx+vuRnMx6TpEn0pjm/xgkmbPgKnc/kUjMVNwfzsANOH+leikTlVl4UCa9v5a9LW+WLUvg3VvUKr9xiOJA5DvoGhf2z7IMY
  template:
    metadata:
      creationTimestamp: null
      name: iterion-mongodb-creds
      namespace: iterion
{{- end }}
