{{- if eq .Values.cluster "ovh-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iterion-minio-creds
  namespace: iterion
spec:
  encryptedData:
    rootPassword: AgCh0cdSkzSBR+IZd/H3sV80SKbUxoJdDaUpE2TRT/lYmzNSMHls+tLyh+yQAzStm4qg8rvYZuCBmbkvVITZ0mrN7RjGFucapWx1xdUDMGawSLT6ntlEbQz+TEuARk7Xi+/h457MSSdhsoogzDrrUGOkE/BmI3lNlbmilSdaRM9L9RMuitd6HsspXfymvZmFhzBay96h/MQhpT1yj3YPq+llzs24EUUnVvZV9kt8Oh9y6rVtefQo5Lb3DnmOCNZCrAbkKXTl2b3lsWz/XROsDcs9fu72wNC4P4c5ykAgoyW+fv8rbHrTIXtrem/Rtv0Z7EVJXvwbfDH4Fk9pOOJwDWkTnYrj7/aTc7jRBh6cBAdGdqKEJKiiIwRf2SEqujFtCrHwJ/oaKobqD3QHHrd3OHb68AdKb4KAdCE0PQ67VIVaQv5gySrMkOlCEt8dx8paotVfIH6rIKd/M+pMd7QLFtUKTv18PZDLY6xJVb4ZeZggvFI8wqwC+CJk0Ik7A3ijx3ljeVW8pjBsm+Ftc/6NR4WlNeRdQNK5dzuSKnwIdw982XCsvQeK2v5l2M9ekqWWsv4ZKSMaZw9Vn1ga+QWfFJHQGDgzgkJWCDQEsG+tWxXG6pgA0nysEuv/fN1EjXKuvZnm9mXTtZCz51L/wsJUZrTaQWebMhahW3+Yd52vfojT2bcE3m35ItnwLcxloeDZdYOjlQf1BWDjIjU9kTb2pIEJBIt315xqU9nuvlaw
    rootUser: AgAPjGnq8VgK0mKNVPvvz83+AlydgpHQmvq6rPIj2C3qN8GmbgePKc/ZcfdLzxowQI7aY/JOn9zMwKO/ecW8bF1zAED+v0VLfkKPYf1Ctxw7eFln4TcjZgaJuWgtQSijdy94MBJBNhFQbXNowipV3tne/ohb5AMagI0UcAwH6kKHdEgfuiQhg8V8aQBNBjkX9EKMoLk0Mz4epmkLAYeOdPV17tJt5NU687IrTmfATzCzP5NFnAVfO9u37lmuicZUEZjjvDG/lwbzFjpXxCRpERKbIdsu9FbctRbrljVFp7/ObRNo2q5UYa4mGaC18vXKIaPKGZswJFnbhGO1TYrbaH+wrebf6Ji4bmIZ7NEdN45YOwrMFqUaVFAHfvUx27GFIujeLKsZ4YLaVkyngASvU2kyEkJ4Wjl1QKZCcQVtahiEH/rQlmiLhyy3T6C6xRW5HXWbfo/1LJYCMgfIfKE86zamSYqBNWX/g7t0K6ZZGGf7BbYf4mbH1zEKiOYtv/gPvGyJgD6f7a7aetLEY0SRsZMI9spj7XwfJMrJumAWuYBqHIIVfW2TsETO0vwr0lfX5HmO4YPyxgq7hrqTx+GH98uxRBI2petXxy1/2R4OCG5YK/9inqeKZfwKxybWZECw8KJL6NEq2Xyn58WZcLYJ9Ay+XqVS+udMlb3jcKX4E1dFkyUEzKv6wDM9a18yozqVioWi2q9rQ+1z8Lx31yA=
  template:
    metadata:
      creationTimestamp: null
      name: iterion-minio-creds
      namespace: iterion
{{- end }}
