{{- if eq .Values.cluster "ovh-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: iterion-firecrawl
  namespace: iterion
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCZpDzKLxwMA69HNyE0Z1BC5Xxh2/TDM8C8b4JpKHv9n0IXocZOCAEEASaJFw0jLjz19weZqGCKno3Q442CEPce+DbA0FUyaRyVNm0ZqtzUqRh1Ad+4x+hlycAqLPcdU12I/6ZhvbTkcA8Yah4G5fGxEdqYy6q9SvW1EqtXH0s1AN2QCf4zarSWsySmDlcM0SHuujHbiiuLI9u7qpOfpkGhcusQ+naUZ2wcCZjCzM/DiNjiJiZnGGPT/k/RcCSIDZ0bAjsKvg5m6FBkRopmINmUaIvl+2cyUWUSdmfSdxcJ4j1BnfidZBtWnsCPPagQqVVveDnpZBsqIlnq+m7u3/rsjzXcN/PbwQqhQj9qd1fDaw1IG/t9D1Ul5Ris25EjQ+c4kVZzC8iZxDQ0HKojKMWj1S329eXmYybfHOWcqOU8OGyZquih33Zl57yRcLjsBGIdVfssmLD/hto9bfNOfRhDFC2Z4sYrwfrmLkl97tIZIu5vteqbEpfMM6rZwpQv5jqywb3CCdzsgS1Cf91xt58d1ipNvqJChUvI80w1R4FSYjd9N3xIdxV9DUuoTPJKxQk4Ll6HQsoQmaYx4/6tRJzpssr52WfnmyzINRyDFWI3OS15V4I/MpxYLhq8958qRTGCOvQW30wnejAOMjeaPNWrQcfeFtnSjWFEBHIhl1ML8w8j4FFOHLWSoP/pdPdOurJI3MiTf+TgL9kVFlOecAFohBSaBl1aU+lvxFs3P0E19LC74RoDe6t5pXv3Kvv7tUI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: iterion-firecrawl
      namespace: iterion
{{- end }}
