{{- if eq .Values.cluster "ovh-prod" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iterion-llm
  namespace: iterion
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgBkYAnpot6IDRm0+WK5s/cOLpYD1X6jmELPE5YTV+l4zMxVuateXCQy21p9dDMSImQjHKHyGR8oEHypJu8Lbh2jaQTR0kLaoGFxeCR5KpuRUkTgJajBDs3mjWAxXxaJAwDv3pp0BsZYmaAtJf/WK0+7ynXIwE3Q+YKkRdKff/U9gGp9K2Mq7NkluNY3XxsLtTs4z/S1eh8luXpNYZua1P6P7CtFkX7My7dd3oCR4RXC92aUM4+xUropH2zznqfPJICg8qNCMnI5BEmbAUm4pTynaiOYXsKVmA/FWlnFZJeWD9w+PGL8LbBrS6BkVt3fPyncvGIYJOWMSIoUkItGSGXFmKzkLNNXAEzyRKhLfqiavdAT5rXUL0G9Z5EhpWu2P3oF/uNz784e8siqU8FUPi7sDd821zKb8LxrgvFlynFquUkJeb3vzDTLb9o5E66d+YUbwe3jx0S/6l5A8NN9eRD62eGKCP2Jm662EE++/UkFdNyg330oDkwe5gFFsfWKF7FBpPomR9xT2wohtEl5f89znRfJHXskSRytFj2UFywdkal/bI5WPQbq0SWdyaYWtcA88Prj+jtyFYHlVRpwxVt1P9I99jOrVpuxNMPG0/yJSK65FTybLX/KSEthI68idRwpNkFsiEa09gpW2hlw7Elij8o+dIQG3c112W5jwNlROORP538VsHtxOG9d4p1oBrkyMSBlxye6mXg1z22bCzakyS8woYS/ZtY2J06/HJdvTESUMEXv2m5OS6GJiY7FtS0OYiQ/sCCQlWdYsmPux/Lm7YN6C71eFI/Tnqt809NljsGGTI5ZnRecBPAi6OKYuFkdRcISFL8etcBBtRg=
    OPENAI_API_KEY: AgCPfbwmfrsOoWiOPXcw9hRDj5Go3/WYbLKYDFzPQNLcsbEotmxOnHXc9goqO7KxfHorbjn3iYrByvVvWJcZ6huDvDhPLOWM2FNwyyM3GCF1b5xUH3xqpk8pR7AxpBGGZBukv8ZnYkvrRjcYZBlwpA1ARAPv8fCcM4L9cZu1CsyyipwEbU0Vr0BJruVSwXdrz6HMPzQQ9KBDl9jvTL8ePdljuwLzcVXN1JnB6RtXet8SM9zvJLAybjQmQUymBWnN30Lbgukluwl47C5IruHOiYjDETIGzU6g3SfMvgnTLPjecEgl69NpN9OfTjiita4X2rS+4NFHtBy5u5DOA16bp1oAWznpKYgPQmmQzmfTHSTJ2MgWZbsT4su1dc9ZHcoCs7x+FJYzoNNrH5tYbevd5oMh1Y4GJEk7KA/wT5+0vqKWlalAd1kheLjup6XaPiwwRpAse3+YR9pFwd8RrEYo4Qu48hlyb2WWwq3RDm63/zo0gMu1ILZIM9q0fcxU5QxQUPKlksOPKK4ADt4Ok1g/jznWTB8gIVaGwHrM0N38OlXtvWihCPNHMHYut4VeyXZxIiHkaaORY+FO1y18U3GnFmP2NuNl1HO1PMhwExbRaYy8o6f7wuq6IBa4RAdlogtw6wRNtbZRbTFe1Z+d0EGHX/+ecQcb0au/nzUAZadHHYu5Ux8kQkhhJrJ+GyGSiB7c4a4Hukp1MgS1PwCRYdfLqCaYDHRMXDntCgJEAMdDTHccODhzPdxJ6we4gIQVnJ3/+LFU/KZoHec7WIcOKtiG+O7C42MQUjSIatHGl/y18hymmIy5osQyvpJS9OfZSHboi1yll8GVBPiEvroOSa/3Kzf+Cgw/1I5IRu/oS5n1sn7i5YMRtVOPenC9jkRc1golPR58s8rEfmzfsEnSFPwraQlP1yvFtcSNNw==
  template:
    metadata:
      creationTimestamp: null
      name: iterion-llm
      namespace: iterion
{{- end }}
