apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name }}
  labels:
    app.kubernetes.io/name: cdtn-elasticsearch
    app.kubernetes.io/part-of: cdtn
spec:
  version: {{ .Values.elasticsearch.version | quote }}

  nodeSets:
    - name: default
      count: {{ .Values.elasticsearch.replicas }}
      config:
        {{- range $k, $v := .Values.elasticsearch.config }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}

      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: {{ .Values.elasticsearch.storage | quote }}

      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
{{ toYaml .Values.elasticsearch.resources | indent 16 }}
