apiVersion: v2
name: e2esdk-dev
version: 1.0.0
dependencies:
  - name: cnpg-cluster
    repository: https://socialgouv.github.io/helm-charts
    version: 1.16.3
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.17.1
  - name: pgweb
    repository: https://charts.ectobit.com
    version: 0.1.7
