apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    component: {{ include "common.names.fullname" . }}
    application: {{ include "common.names.fullname" . }}
  name: {{ include "common.names.fullname" . }}
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            component: {{ include "common.names.fullname" . }}
            application: {{ include "common.names.fullname" . }}
          name: {{ include "common.names.fullname" . }}
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            runAsNonRoot: true
          restartPolicy: OnFailure
          containers:
            - name: {{ include "common.names.fullname" . }}-container
              image: node:14-alpine
              securityContext:
                allowPrivilegeEscalation: false
              {{- if .Values.command }}
              command: 
                {{- .Values.command | toYaml | nindent 16 }}
              {{- end }}
              resources:
                requests:
                  cpu: "1"
                  memory: 1Gi
                limits:
                  cpu: "1"
                  memory: 1Gi
              envFrom: {{ .Values.envFrom | toJson }}
              env:
                - name: STARTDATE
                  value: {{ .Values.startDate | quote }}
                - name: DEBUG
                  value: {{ .Values.debug | quote }}
                - name: NODE_OPTIONS
                  value: --max-old-space-size=8192
                - name: DESTINATION_TABLE
                  value: {{ .Values.destinationTable | quote }}
                - name: MATOMO_SITE
                  value: {{ .Values.matomoSiteId | quote }}
                - name: MATOMO_URL
                  value: {{ .Values.matomoUrl | quote }}
                - name: MATOMO_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.matomoKey.secretName }}
                      key: {{ .Values.matomoKey.secretKey }}
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ or .Values.pgdatabase.secretName (print (include "common.names.fullname" .) "-app") }}
                      key: {{ .Values.pgdatabase.secretKey }}
