apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs
  namespace: enfants-du-spectacle
spec:
  storageClassName: sc-classic-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
