apiVersion: v2
name: metabase
version: 0.0.0
dependencies:
  - name: final-appset
    repository: file://./charts/final-appset
    version: 0.0.0
  - name: metabase
    repository: file://./charts/metabase
    version: 0.0.0
    condition: metabase.enabled
  - name: metabase-matomo-sync
    repository: file://./charts/metabase-matomo-sync
    version: 0.0.0
    condition: metabase-matomo-sync.enabled
  - alias: metabase-matomo-sync-preprod
    name: metabase-matomo-sync
    repository: file://./charts/metabase-matomo-sync
    version: 0.0.0
    condition: metabase-matomo-sync-preprod.enabled
  - alias: metabase-matomo-sync-widget
    name: metabase-matomo-sync
    repository: file://./charts/metabase-matomo-sync
    version: 0.0.0
    condition: metabase-matomo-sync-widget.enabled
  - alias: metabase-matomo-sync-landing
    name: metabase-matomo-sync
    repository: file://./charts/metabase-matomo-sync
    version: 0.0.0
    condition: metabase-matomo-sync-landing.enabled
  - name: pastek-mirror
    repository: file://./charts/pastek-mirror
    version: 0.0.0
    condition: pastek-mirror.enabled

