metabase:
  enabled: true
  fullnameOverride: metabase
  cnpg-cluster:
    backup:
      enabled: true
      barmanObjectStore:
        destinationPath: s3://cdtn-prod-backups/metabase-ovh
        endpointURL: https://s3.gra.io.cloud.ovh.net
        s3Credentials:
          accessKeyId:
            name: &s3secretName cdtn-prod-backups-access-key
          region:
            name: *s3secretName
          secretAccessKey:
            name: *s3secretName

metabase-matomo-sync:
  enabled: true
  matomoSiteId: 4
  startDate: "2025-04-01"
  fullnameOverride: metabase-matomo-sync
  cnpg-cluster:
    persistence:
      size: 60Gi
    clusterExtraSpec:
      postgresql:
        parameters:
          wal_level: minimal
          archive_mode: "off"
          max_wal_senders: "0"
    backup:
      enabled: true
      barmanObjectStore:
        destinationPath: s3://cdtn-prod-backups/metabase-matomo-sync-ovh
        endpointURL: https://s3.gra.io.cloud.ovh.net
        s3Credentials:
          accessKeyId:
            name: &s3secretName cdtn-prod-backups-access-key
          region:
            name: *s3secretName
          secretAccessKey:
            name: *s3secretName
