apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: secret-key
spec:
  encryptedData:
    SECRET_KEY: AgAqrEvaYpUkQLNn27utpzD38+kF7OqGZ1YKOPrKBga9wLV+NXBtRIG8z5aR0RDbbN71wt7MIaWIgQe4DlDpYMK2evuMxDiO1P2aqZ9sXYDPSkkPvO1jWNzV3ZltFKGs1peYaWlAmxDed6x7mgfj/PlWaIXMRm9NvAVL0vpCZLFxbdVZ1qjdMF9q3nUZh1kdeEhVRjHkx+IQcT6uqOajLB63XpwBG5nsFLVkrGeSqJ5vnP9WToI+o9yjF+zlsHOkmb11o+8lxxWyQQs0ZHK3L6ohDRWf2Ka6PeG1okMNP4KoewA2S8AHxbKT5AYNG4g8DtocIpV3h83P9uIovvKUxgSe/32Var6WY2wtaQv/KW7UbHSjmgiAIfQnM9fQLUBvbIXI6qWRUlkWrVDjxNf7nVieNQXzxFnwtrylbuqTaoM+v14E5NgqfOO/MsCt7BbUZbaKf1dq+JN1lzpMa/tCZ9+XJiOEFJiB/c0MkgZOOBlkemjXqhQ1bjj4H4ndU99tZpAUS7fo1BbvKXKx9Py8BDDKGdD0MvVL5dJ92Oe3sR5RFCZaGZWZiEsNk76SuhfId7WUDv0qyDfUJm/QpQs23JJeNUm3T74bwlRbWSBsMkZ/xrFxX6FbUKcNqBxTKAIOPIVLLZJpUxBO3LLnPu+WGXtWH+WC0gRDwlDAw0s92pBVmbmw9JzeYRJnmf3b7s9UQLnzlVfHuWQwiELDiNFY/PllT+pxxekJ29Iv8sjL
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: secret-key
    type: Opaque
