token-bureau:
  image:
    # tag: latest
    # pullPolicy: Always
    tag: v0.0.6
    pullPolicy: IfNotPresent
  replicaCount: 2
  existingSecret: token-bureau

  labels:
    oblik.socialgouv.io/enabled: "true"

  deploymentAnnotations:
    oblik.socialgouv.io/webhook-enabled: "true"

  podAnnotations: {}

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  ingress:
    enabled: true
    annotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: token-bureau.fabrique.social.gouv.fr
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - hosts:
          - token-bureau.fabrique.social.gouv.fr
        secretName: token-bureau-tls

  # resources:
  #   limits:
  #     cpu: 300m
  #     memory: 128Mi
  #   requests:
  #     cpu: 200m
  #     memory: 128Mi
