token-bureau:
  image:
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  existingSecret: token-bureau
  ingress:
    enabled: true
    hosts:
      - host: token-bureau.fabrique.social.gouv.fr
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - hosts:
          - token-bureau.fabrique.social.gouv.fr
        secretName: token-bureau-tls