token-bureau:
  image:
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  existingSecret: token-bureau
  ingress:
    enabled: true
    annotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: clusterIssuer
      kubernetes.io/tls-acme": "true"
    hosts:
      - host: token-bureau.fabrique.social.gouv.fr
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - hosts:
          - token-bureau.fabrique.social.gouv.fr
        secretName: token-bureau-tls