apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "token-bureau.fullname" . }}-permissions
  labels:
    {{- include "token-bureau.labels" . | nindent 4 }}
data:
  permissions.yml: |
    {{- toYaml .Values.permissions | nindent 4 }}
