apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: metabase
  namespace: startup-les1000jours--metabase-prod
spec:
  encryptedData:
    MB_ENCRYPTION_SECRET_KEY: AgB3Mort8kPZHJ+tw8a4N6utX6tpAKicue+gvtxSnVQfulvnA3xcNlX6MVLqxuV6a3HmbURu+fTDn3lqxZdyS1+beSSJhbkrIQFQtA3qHCi63q/271sjCiJy8ZRWUMPKeU2T3pYgztxdj5kWJP8MBBiIKzl8bjJ9OFGfT/UZoaqHY/7XZyo22eOUYIy0h30CnN+tUlkaj7RPQF2dQPBARmXpds/qgcik0tqmGtK8KxTuhFCVcgws5XQE64TxQiaaU7WA2/So2KrOAxRBxDfX6qbgYEb8VNraOWr7tMpk+EFdq6E9bhJ9ovtz1cbVP41q+RInmyDP84dUyIi3HPxhWBhrXne00OoVqRxzwpsDhLlIbMY2A5URjQhEnZI0c7dPdtGeeiNSqKhkNS5tF1ey/AyLv+NqR84XVISaU0xGX3ljN6+Ia8X5VD4N3BWda+MQdQBKK+KRNlY0YJpD6T1jzSZLUzgQ4Tf1K47xHcE6oD1Nw+FfrvKojFDnmHChhQvUO3oJrl8WzeF3Au4uwgwaD+PIjzujSQ7FJ2XmGNzSj1bSlDnmBOScre54PRCt/eYT2zBxI9Da5JdAaNL8JLF4rXtY77kLC2GRxjL5v3PJUKpf9vTarJuaWShoN/C2SGvx5DwsA3JbqaBYYCVKiklyfJBhP2xcEQ9YJvDDLBZUamoPbyTSfDZ9SNjrx7My+wl03qkm/LRKzG2nxhZ018tjyKwwEoF7aNnORUKovf7xIEkWOg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: metabase
    type: Opaque
