---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: buildkit-operator-s3
  namespace: buildkit-builds
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBAg2flghbtbnwLaD1TqS8sw+uV97IJz1VEhUwQQZptNDoQ6z/wBGHeW6YweYY02VY3pXwKGe3hgwK4c4ki7WdFB05HsSJAWwQkn9FNE4mVC7SrpNsveyIjI8heC+bvJjmx7Qcg7B0zInZTfzDyI9PwHTCy9X3g2b/20lH6c1AaHFqAZb9QsrUvAmMuEXaS4YZY4yBQAIQTf5sZG36KA8uCxxn8BEiPJGn/k8dFSaIh1fqbFYj8FGysxynox9RG2Ncc4NL7kkPJmcioavx0nnirVX/Bz9AeCghT0DvIhVeQNKc+mpdz6JVN/JFLgtXpxKdkfiESqnJpW7wTNm7VnR7uXCUv0hNgvMKbE91HXz8u6S9zQZsx+g0tZvEJghoYrYf2e5PKMhHkJYUBwsElRWUqgKGVnvYJGfUDamML3QYAYLt8D6uYSz8yVSQopIYDK4EMVcIFkbdeRc501hfk3uHEcs18rlqLTUxd3mR604uzsvqWkb5VyrCSZqKiYwJumphE7k02hKfezw9DyB8N/QZ+5ZVxtEfm1SnN9ZlROYs8UY4fXfaQdBo8+A9dGzgC4ccKEcKJ/gqOZWu/seIkzTNRaMX00WjwIwR6kiTFvb+Vm1IQdAgj5l8vxZ089xTfxnk94HiJ/Dy5Ffr12Bb6kh51PRkfiwD8bOTikVgqql9e5ZcRx0FCcJFK29JNUIw+9+q5WXvdV8JAfDwggD1OP/Hk7RKx1l/ZOK8n3IWCd5d1Eg==
    AWS_SECRET_ACCESS_KEY: AgAKLhFMcgpJBFrdtv/Q/ix1b430Z9513gm1KObEpIFDGRJrDyVxREBi0Qwx5HV0j5EIWcdkaAzVOwSNqAsFc5yKcuYfIO99QNM/mt7tjD/lV/vbCw2cBf+QV7e2Z44WoHLTXINntECg+4HOVLD8qZfoVDUKa04PQB6tPcg6olW70U3t73BR4Bd01Yl7hTm9Xo5/DK+617xugkt41Ugc9JKw0338eKLS4HgemmZy0ahT8EXguDJmARJb+tdjCVVDJiF+Hf7CTo8H1nl/ggLl+8URWvsrBuo684EnYDC4VcCTjmoheqQ4vwpWI0+uJ4jwixuC42pLVU6ujzeKkKspWWEP/32vput120iz3DR9iu0bGkoBmosiY+Nskovuh/oItDXdZXrZhlWIwN8lNlH0I5qb9+Y8LQQwKjnraSzRoq871QhBD4zTMD0pyoLMmKkzcXm1wOmNTXaPloIsxnNHZ6hwxbj8HETFwiTXDSI0Hm66NtxS4DG41aUWooFE+opD5QQdbjlWIr+SdV//l9e6hE2B9GeDiHG/1RVdq0Tr0IpfvGmJuxtL5cLqk6qEdhE6JlykA4hjcRvVv4YosMnbTtustgeOy+DEnxKyXM1Z2jcihGeWigGvghwcZXyJ6kdtiYOuSwCjMEaOLcE4pIjJPhaQnh4xrBY7dLete5elZByrBQVgf1HXO4Eh7vFcD7RJ0g7UFGUt6wap3luGZSW5CmqXKWFC9s8zLZC+TZvlZh4QaQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: buildkit-operator-s3
      namespace: buildkit-builds
