{{- if .Values.existingSecret -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "token-bureau.fullname" . }}
  labels:
    {{- include "token-bureau.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "token-bureau.selectorLabels" . | nindent 4 }}
{{- end -}}
