apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    application: cdtn
  name: refresh-views
  namespace: startup-cdtn--metabase-prod
spec:
  schedule: 0 2 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: cdtn
          name: cdtn-cronjob-refresh-views
        spec:
          containers:
          - command:
            - psql
            - --echo-all
            - -c
            - |
              REFRESH MATERIALIZED VIEW CONCURRENTLY metabase_model_106;
              REFRESH MATERIALIZED VIEW CONCURRENTLY commentaires_utilisateurs;
              REFRESH MATERIALIZED VIEW CONCURRENTLY visites_uniques;
            env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: ovh-database
                  key: dbname
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: ovh-database
                  key: host
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ovh-database
                  key: password
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: ovh-database
                  key: port
            - name: PGURL
              valueFrom:
                secretKeyRef:
                  name: ovh-database
                  key: uri
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: ovh-database
                  key: username
            image: ghcr.io/socialgouv/docker/psql
            imagePullPolicy: IfNotPresent
            name: cronjob
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 40m
                memory: 64Mi
              limits:
                cpu: 40m
                memory: 64Mi
          restartPolicy: OnFailure
