apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  namespace: ozensemble-site-preprod
spec:
  storageClassName: csi-cinder-high-speed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
