kind: ConfigMap
apiVersion: v1
metadata:
  name: charon
data:
  CHARON_CLIENT_0_WILDCARDS: |
    http://localhost:3000,
    https://secretariat-*.ovh.fabrique.social.gouv.fr
  CHARON_CLIENT_0_PROVIDER: github
  CHARON_PUBLIC_HOST: https://charon-secretariat.ovh.fabrique.social.gouv.fr
