apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: metabase
  namespace: startup-vao--metabase-prod
spec:
  encryptedData:
    MB_ENCRYPTION_SECRET_KEY: AgADF5uGkTp63pHZky5crGdlB9DLviUo1T3uGfvLbiXbASo3j10kQKwaYKysWaCSV3cxdJ2/T69MU5cZfMGcW04ASLuWmVUfdzcp/66zVLwZbVn/0pmukFA8SaWXQ2QACXIenrDurW1/YywCmfgWiS/5JgPdw1sZywn3lRJaqjKO8qFizLkOrLvVW6WQnVzSBUvSv8A8lLJOsPTYXwUZkm2ZZ002cgq9V42IFWfE4H5V9QTEIY+AZlIJYTjmq04afTxXyz4sy3uqkuAjYmAo8AK8cFCAcXObOXO5I6LmyYzLk16XbxFWgtcFfbLkvBwp9i0/C7zE8HqOHn/lbs1K/l6eoDiTycibia04FR177bA3vhJzuAuTLCCj393ouGx6eyOI3z2XWF2E7o71YgGwn0IIcwJbngJxW7qJf0uw+dX1Tv6k5T/rJUHK0ImfiPD3AmSc7NYUWogR727FVFlEEk62CbYIEnY5yPxnJhcJq//HF6Z42RziqpOf1lSmzGQtSq2MyhVj+56QeFNjTF9hseU/I1G5BDO5iLPwc232TROXfgqE4pzbTQ6ZjQo4GHxJA99c1vk11Lcdvkf/mKEa6gFSc/Yj7rDksU5pjpPuYlSdmPyCveg1NlJprpnPPy1wE0PHGFJOOCYk23FjdMlqAV4NApEs046mKvLvmp+/z7yuk7kAc0kU7W61WJ8dhPEtIO6p9LHQ+MwfeKZqdiBjbDFXf+9lGXNfkbnnGt34wuUaLJEQU/+vHo/BnJxNUA==
    MB_EMBEDDING_SECRET_KEY: AgBle8qReD2keGvKw4pFbFGcs5EsmYwNpKdEFK+v0/cm5DuuDHW9eAhpoRNaCBW5QuIlHpSNNQUPFuUpbvE6WayCjLNm+plx0Wbls6OTjvYtFVXjeYhxTxzcP/8Tl12nXmPo6FWtF1yekwM2BSNY5bQBDyctJTIbXZ6q/Yqg0WHKwbkQcAoXTgw6JnIxIrv2J4ncl+NQ6XYcEY7zmioxQ8d0OPtVN1VkIinvyy3A2/mz31HN5j0mf83d7LF+kmIRZX306nwjSYQ26t1VrwSVCWWuSYfRn2jmdNPDhIY4eqKNaa+zEbZulpl+cZ4O8M3ooVvPaFuaUoXimA/IZYKkaxvl75Y0MO8NE/Rz0Q5G7m1Gv28dH2IpDRbZ+34cwlW4K8r5mZvPrk8zsQAGJuAvpAKGerT5vkIYc6UeYdV1Nq5cZ9saD7jOjVYZWmXa9ilALoABv3RLJvQww4JDu6ckKbXUpEgWlEfO9dJCNCHOXDxuVK+7GJx8ARqHTdvQuGiEUgk2KFOPiwQw7WrhLh3saEuEKPNcjHpxWMuPIhvaIxXWxx14fwIDprlGyDP9wywxRtKJ+VDR1EUFhwb5L9pCSvlerhbXIskjffaDcyqOIbgeq5tLbvn/+0DRWP8EMVn1dRjb/VNP24dv9DN4ypZ5ABOiAhm+moFxpx9wEECqEBBNcCzO9HSD8Jb64CpJp47vTKl5EhWvzKBA/p7E5etDGaBGvrZbPPbijdNdKt2zTw6nen8kUWJPyMsm9/aA2EI6+QfduUjIyx4b6Y+V0OMz3T5N
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: metabase
    type: Opaque
