{{- /*
This Helm template generates a Kyverno ClusterPolicy that adds a specific label to workloads
and allows adding annotations per workload kind via Helm values.
You can enable or disable specific kinds using the 'enabled' flag in the values.
The kinds are specified as keys in the values, and apiVersion is optional.
*/ -}}
{{- $hasEnabledRule := false }}
{{- range $kindName, $kindConfig := .Values.kinds }}
  {{- if $kindConfig.enabled }}
    {{- $hasEnabledRule = true }}
  {{- end }}
{{- end }}
{{- if $hasEnabledRule }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-label-and-annotations
spec:
  background: true
  rules:
{{- range $kindName, $kindConfig := .Values.kinds }}
  {{- if $kindConfig.enabled }}
    {{- $apiVersion := $kindConfig.apiVersion | default "" }}
    {{- $ruleName := "" }}
    {{- if $apiVersion }}
      {{- $apiVersionFormatted := $apiVersion | replace "." "-" | replace "/" "-" | lower }}
      {{- $ruleName = printf "add-label-and-annotations-to-%s-%s" $apiVersionFormatted (lower $kindName) }}
    {{- else }}
      {{- $ruleName = printf "add-label-and-annotations-to-%s" (lower $kindName) }}
    {{- end }}
    - name: {{ $ruleName }}
      preconditions:
        all:
          - key: "{{`{{`}} request.object.metadata.labels.\"oblik.socialgouv.io/enabled\" || '' {{`}}`}}"
            operator: NotEquals
            value: "false"
      match:
        resources:
          kinds:
            - {{ if $apiVersion }}{{ $apiVersion }}/{{ end }}{{ $kindName }}
          namespaceSelector:
            matchExpressions:
              - key: field.cattle.io/projectId
                operator: Exists
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              oblik.socialgouv.io/enabled: "true"
          {{- if $kindConfig.annotations }}
            annotations:
{{ toYaml $kindConfig.annotations | indent 14 }}
          {{- end }}
  {{- end }}
{{- end }}
{{- end }}
