metabase:
  annotations:
    oblik.socialgouv.io/enabled: "true"
  host: metabase-domifa.ovh.fabrique.social.gouv.fr
  ingress:
    annotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: true

final-appset:
  importSecretsFromStartup: true
