{{ if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    {{ if .Values.namespace.annotations }}
      {{- toYaml $.Values.namespace.annotations | nindent 4 }}
    {{- end }}
  labels:
    {{- if .Values.importSecretsFromStartup }}
    sre.socialgouv.github.io/startup: {{ or .Values.startup .Values.global.appset.startup }}
      # sre.socialgouv.github.io/secret.cnpg-backup: example # https://github.com/kyverno/kyverno/issues/8025
    {{ end }}
    {{- range $secretCloneDef := .Values.importSreSecretsList }}
    ## https://github.com/kyverno/kyverno/issues/8025
    # {{- if kindIs "string" $secretCloneDef  }}
    # secrets.sre.socialgouv.github.io/{{ $secretCloneDef }}: {{ $secretCloneDef | quote }}
    # {{- else }}
    # secrets.sre.socialgouv.github.io/{{ $secretCloneDef.from }}: {{ $secretCloneDef.to | quote }}
    # {{ end }}
    secrets.sre.socialgouv.github.io/{{ $secretCloneDef }}: {{ $secretCloneDef | quote }}
    {{- end }}
    {{- if .Values.namespace.labels }}
    {{- toYaml $.Values.namespace.labels | nindent 4 }}
    {{ end }}
    {{- if not $.Values.namespace.labels.application }}
    application: {{ .Release.Name | trunc 63 | trimSuffix "-" }}
    {{- end }}
  name: {{ .Release.Namespace }}
{{ end }}
