---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-runner-controller
  namespace: arc-runners
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["actions.github.com"]
    resources: ["ephemeralrunners", "ephemeralrunnersets"]
    verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-runner-controller
  namespace: arc-runners
subjects:
  - kind: ServiceAccount
    name: arc-gha-rs-controller
    namespace: arc-systems
roleRef:
  kind: Role
  name: gha-runner-controller
  apiGroup: rbac.authorization.k8s.io
