#!/bin/bash

# Function to process a single namespace
process_namespace() {
  local namespace=$1
  echo "Adding annotation to '${namespace}'"
  kubectl annotate namespace "${namespace}" kyverno.socialgouv.github.io/trigger-manual="$(date '+%Y-%m-%d-%H-%M-%S')" --overwrite
}
export -f process_namespace

trigger_kyverno_for_all_ns() {
  echo "Adding annotation 'kyverno.socialgouv.github.io/trigger-manual' to all namespaces in parallel..."
  kubectl get namespaces --no-headers -o custom-columns=":metadata.name" |
    xargs -P 10 -I {} bash -c 'process_namespace "$@"' _ {}
}

echo "1st pass"
trigger_kyverno_for_all_ns
echo "2nd pass"
trigger_kyverno_for_all_ns
echo "Operation completed."
