buildkit-service:
  image:
    tag: "v0.22.0-rootless"
  resources:
    requests:
      cpu: "6"
      memory: 12Gi
    limits:
      cpu: "6"
      memory: 12Gi
  init:
    fixSysctl:
      enabled: true
      mode: initContainer
    permissionsFixer:
      enabled: false
  dns:
    enabled: true
    nameservers: ["1.1.1.1","8.8.8.8"]

lb:
  enabled: false
