replicaCount: 1

image:
  repository: ghcr.io/socialgouv/token-bureau
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to appVersion in Chart.yaml

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

labels: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

deploymentAnnotations: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

resources: {}
  
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Secret containing sensitive environment variables
existingSecret: ""
# must contains GITHUB_APP_ID and GITHUB_APP_PRIVATE_KEY

# Permissions configuration
permissions:
  # Default permissions for all repositories
  default:
    permissions:
      contents: write
      metadata: read
      issues: write
      pull_requests: write
      deployments: write
  
  # Repository-specific permission overrides
  repositories: {}
    # Example:
    # "myorg/*":
    #   permissions:
    #     contents: read
    #     issues: read
    # "myorg/specific-repo":
    #   permissions:
    #     contents: write
    #     issues: none
