apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-creds
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgBR7xkvA9sYX0OnW+002u20/HarCcB4srdmvQI6Xr3aLpxw9Bw+XN3461BCGcmEWTNYMQmCcE1CkpmtP1+LuT2OLmPlcTInRgWWMicip1P9Ye8MszKdV6rZmJ9mYWim6L1H5neIL8pub4m+SdjbLLFdGQwv9mX8APlp/7us4m/RcCUK6sCmtPwpBKdwhgPc6/ovR4/AYoOUTkZC6w8BDz8iRIFpe57Ppe7pTge626oxjUiK8s9BAkTEgTR+WQfHGSSNTO/5PBAO6QFzCItnpuka+OzQiSetp++Wi3MGlMzXVfgHwXBAZMCA6mJyR4GiWEIOI/GD8xl3mJuW6X02wBQ0YW+YNIF6H5mcsX1GwcQWdsPXO2iU0r4qZo6UeHS6N2f2d1+y856FXFnqbC4/XG8WoE5ePsaiXRZzq9M7eMN8d4H6RkNxCm8Kr6j9RX6hTC4AHavzVzW6+ZHF+Cqv/O9KbKfvWUzf7eSSZzmXSTF2DR0A6MMarpjer18XdqeuqYEzLYzygcceT266sbw9+4XDsvyCVCY97Mf4YkhepmOTn31/UjUh3b0fJ7DDxsAQAnoinCW8PZuDnbwyTn9Oad8I08XQMe1wvWpEAGukW53y6g5GOIHgRjD2zIh/UKN4Qzc02OKRLVq8hjiN1HcMXkVqerhk1aDqWXk6f3vWGiXM4Y/5tIengvbNmTlr40XZ/zH5Msd8bgG0agVXGDuTptguXZHrjiSwy2d6w4XgWJuOIn3fO++fCH87y9IZAIN10KHqV9LfsraZpeFgEIXpWLEP77xPFBujQyDsHwKQP1gEknfBa1U8WxnqS43G8b8kjPW8rbPWtn+dtF+ktzGcIfjNDFZaJda0
  template:
    metadata:
      creationTimestamp: null
      name: admin-creds
      namespace: vaultwarden
    type: Opaque

