apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitwarden-redirect
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/permanent-redirect: https://vaultwarden.fabrique.social.gouv.fr
spec:
  tls:
    - hosts:
        - bitwarden.fabrique.social.gouv.fr
      secretName: bitwarden-redirect-tls
  rules:
    - host: bitwarden.fabrique.social.gouv.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vaultwarden.fullname" . }}
                port:
                  number: 80
