apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smtp-creds
  namespace: vaultwarden
spec:
  encryptedData:
    password: AgBiYo1Q4Kd44WS9I58ai0kl9VwzOUHwFCh/XJqO8n8ZJ5/ZSo3LSh3231ebpPGiJWX+NMAmGCCG0yRbqnE0bZupVMzru+ht96S2wIiZbo0crbq9PJspP/2z412YAoRyX0csdYF8KDjR/ZOSqXYYQUhE94Znv5OHa7ScQjoHDhcZj/3uUwClOrTmrBO/+wLLEcYWjRwh9MZTJb5KDFYUmyLUkd0NTvUck0YUwycW6/Dn8pgIJ66k8uG2td3usSZhzittef8hg8iWHvzx438z43r53IXLvOscDa+mMRUKI633LYdLXdJZkly+xZFknMxMsf5gKmlP5HZn9UWqPsMv8Lq2xnSf0eY6ZeaAtvRsSVJDOVnnxyE0Koc/9xA3BU+6QRANccVdeIFR0QKvSqcalYS6kIY87GLN7flVg4ZWyuMZtr8g6MkjZFsmZx6WPn+nk3t38by2UxPfA78kPAzzlyKBapbZO5GB9W/oiTzKj7vuD4l/lJC40Yl1PWxtmULcJOgXVh1aSHbfF2Tb9li2eXn4I9d/WF454bM9Dgyn3s26pnAYnHUJygkWMq+vN6SV8jHZgAl0cSdr+x3qFsOcXevc7sRmtrHaIAIZMa0ds9prNtGwneNDdVPU5spK9J0IBVmtf0NIbAv65ti+oSkgRlgz79iMc8VOUfzSly8wlhe80t2lq4Ttg6IRrGZGEwiN/YppTMhSk4Jl2ubgD73y46KwsVFlbbjVulLPPcYsAkM3PA==
    username: AgBZxrGmPe52mgwQLcPI6/5HWZoUkLe+/ZBoenqA2smSWBsUYcw9b0gIg8FRC2UzcLSrIHNdYjWf778fPARI0sZLwKulCR74sIkA37cxYbi7L/kQPXQt36ykWnmm+3zedTWLxSrDkpfJFQWmBfN9gzy98OjEBO2+V/MRJg0MMF8iD0Vgt6a9y+jUqLnbzjg/4fCOj+hMSIhrxTrTZd6SDi98rbOx1hEmquNwqbpCDY7EBvG5euKn4UwP5MmRbTqPZs/aejCmJGERfxTNW83e/CWSfoBolg8sUiChp0QpatKmOoBW1+UdgdSAMqXcgCp5tu3zpkpqvJah6jm9m10S/hKMnnOVWo9W1VQXqv6s+LEueGGZo3cUdOa4agZfpmm17jYLB+EfWGiULZdOYmaSQ/9GIl6oC1v+WVw61XsZll+87G/SgpCjbx8xeXQArw6deR9kFuPrMIq5xAKMoSdoGoJW/XLrRRQZ4THBSELx5GW6NO+RWtwjxTOV5FU+6u+WQza2MSGUEg9KdEP0yLG+xYpRX9n7abVA3wvyHrGT8JwLIp30R2NjI5i8cJNoO1SL8OGI6LaBSHkKp6OU+5U4RuaDJp4ll9IMrJZiNiCq3BlvTRhlSJOM4ybiW5aKKjKOnNVyPp+dcUbRBHH3hS/7UwRmlZCmPbnGpehSxVHSlvkvRaL87r3mdSQn9SzuHO9mQpjFwuM7+HlkM1IKQkInFC9Jiz6/sUQWpk0PEnTFipZLlQ==
  template:
    metadata:
      creationTimestamp: null
      name: smtp-creds
      namespace: vaultwarden
    type: Opaque

