apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  namespace: tumeplay
spec:
  storageClassName: openebs-nfs-hspeed
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi