cluster: ""

image:
  repository: ghcr.io/huginn/huginn-single-process
  tag: latest
  pullPolicy: IfNotPresent

web:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

worker:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

env:
  TIMEZONE: "Europe/Paris"
  FORCE_SSL: "false"
  NATIVE_JSON_COLUMNS: "true"
  DO_NOT_CREATE_DATABASE: "true"
  DO_NOT_SEED: "true"
  IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS: "true"
  SMTP_DOMAIN: diffusion.fabrique.social.gouv.fr
  SMTP_SERVER: smtp.tipimail.com
  SMTP_PORT: "587"
  SMTP_ENABLE_STARTTLS_AUTO: "true"
  SMTP_SSL: "false"
  SMTP_AUTHENTICATION: plain
  EMAIL_FROM_ADDRESS: contact@diffusion.fabrique.social.gouv.fr

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    secretName: huginn-tls

cnpg-cluster:
  instances: 1
  fullnameOverride: pg
  postgresqlParameters:
    TimeZone: "Europe/Paris"
  monitoring:
    enablePodMonitor: true
  persistence:
    size: 5Gi
  image:
    repository: "ghcr.io/cloudnative-pg/postgresql"
    tag: "15.3"
  clusterExtraSpec:
    enableSuperuserAccess: true
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 1Gi
