metabase:
  host: metabase-cdtn.fabrique.social.gouv.fr
  ingress:
    annotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: true

final-appset:
  importSecretsFromStartup: false
  importSreSecretsList:
    - matomo-key
  namespace:
    labels:
      sre.socialgouv.github.io/startup: cdtn

metabase-matomo-sync:
  cnpg-cluster:
    annotations:
      oblik.socialgouv.io/min-request-cpu: "1"
