apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    github_token: AgB3crbnBwn7pnTDVHec6XyMGEC9HWgZkobhiCDGivDkSC8VjbkYZwvqpsk0tSpC58VOtcUAApvbfEfk2UAPiOerKQKUG2pyPa4Es7WkwZzHGcg+guOzYhdmimGkJAV8JC1QD8FmBCdbVDdZGtX1juA2x+Dew7tRiSoU0oWwbUFXrPYRFiyS1k80BFbrQTLiQ8n6XGNyctlEEt6fUWuqH/088djyh3y1OSAPLbQmWQlLaqHdqZfonUCPaXjIx/pLtpTddtBxmyi2SsQuNWFpeOie9aWp4Qgy5HL62OpEqP96JNLAMBGdW2vCBibS7ZkBFF0tx1ZSUEhlyAiDY+b0hmXvfYxbrNx3G9Yl2LhNlJzc0BJGOiS3XpUVz55MA6sF4AGOnIf5wvvCk4nAHsmRsp2vq+IAPlbZMsrLbxKCFZ08Ar1Qg8KcirYkMZNH6Jo4Ga8ok+YaUNTtJ8fOpn8TadndC/9X0PN/f+U8tKcPzUv7kAI56byS/QDRVmh2lYKYm5TBB3NpwSWJHIFCAFcEUynem7mSWB12V6OA0ETM1u/5owDmGinXFdq8WGCnuB49Pj3MCsvb4SAE30HCQFr+taIaJpBjLvatHGBTLEY6+yCC1+B889epfUJlAxhOefJXj6Pdd1/FAiV8HC6oEeo9M73Zhfw/6xfsCE/pWn0o0ncWq1rofci3YbezhTyDIs7cLhqHIlql1mdX1CaTZPB2B1+B+gMdgTcI7YDk1C0vxvh28w8ww3xzcbQa
  template:
    metadata:
      name: controller-manager
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    type: Opaque
