apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "no-package-malware.fullname" . }}-internal-only
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # Apply to all pods belonging to this Helm release (including subcharts)
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}

  policyTypes:
    - Ingress

  # Allow ingress traffic from:
  # - pods within the same namespace (podSelector: {})
  # - namespaces labeled as ingress controllers (e.g. ingress-nginx)
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              network-policy/source: ingress-controller
