apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: no-package-malware-mongodb-key
  namespace: no-package-malware
spec:
  encryptedData:
    keyfile: AgBHBswiGezLZplASC2ABDJDZHzBHTKHCgCICPMGadvKa7IxjjlUZZi5fDPtvtc2V9N/Y4d8S/A5yx4pKVPAGbg4loA8HYf2rz6Gje/oTKYaKh4Hx85sOOdDpeYiyovDtq57QhaAWR45n81VHhyQdYTQMYo3a91y4+7HUefGa5PRIZILI7NiHCmFflLIdR5VVv/X805qaU6AQeGUav1+IFX0kT4HkgSRQtVlipgvkRNfoEy4jEprk4xMPVBOSAoN4wqP5f1xRzVIH09slTnyZ4XNDyImv1QmijK4JydXMPScOr0Qq2hIEuKbYPC+aA9Zb7J/kFDgFAlLDlr8YXCC8F3/OU+drfUwbaqCidIDzwUC6pGlllo5IfwWNAAS9xeqDK/gTjSky0cKYV3BNEws5vbQ16tXDrdh96dzio+S5rLgF/wScQl/2IMhGeuuIxTzUSf6fuJAXsI9eP03smwgUUqsAI3IVbXdDLK9DLeYzbel7/ubP02AtxnK8DsL0CB6G1XXFYjhcucdR4Tg8OHwMfgwkhYZLXB5IPZc76TghTm+Ii1n2xjLAq+oks/JhgCCZAwUcCF6Yjt0GF1s2sHzVIj13gxjSAdR4XNJhQblzIeyd1wp4nyEaxsv7nX4VUkRJFp0B0kvCAesXDyN5hFa/VvJZTqEoiuC5Vs+OpYr0SwCo73tJfFyKA0yEjQSMJ8YHiVc84Ak/+d1Ut7JRR4We8cSapYh7+ea4+BsADtvjh0PmGyXKxwofN1Q4Cd63g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: no-package-malware-mongodb-key
    type: Opaque

