gha-runner-scale-set:
  githubConfigUrl: "https://github.com/SocialGouv"
  githubConfigSecret: github-token
  
  minRunners: 1
  maxRunners: 10

  controllerServiceAccount:
    namespace: arc-systems
    name: arc-systems-gha-rs-controller

  template:
    spec:
      initContainers:
        - name: init-dind-externals
          image: ghcr.io/socialgouv/actions-runner:latest
          command:
            [
              "cp",
              "-r",
              "-v",
              "/home/runner/externals/.",
              "/home/runner/tmpDir/",
            ]
          volumeMounts:
            - name: dind-externals
              mountPath: /home/runner/tmpDir
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
      containers:
        - name: runner
          image: ghcr.io/socialgouv/actions-runner:latest
          command: ["/home/runner/run.sh"]
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          env:
            - name: DOCKER_HOST
              value: unix:///run/docker/docker.sock
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /run/docker
              readOnly: true
        - name: dind
          image: docker:dind
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          args:
            - dockerd
            - --host=unix:///run/docker/docker.sock
            - --group=$(DOCKER_GROUP_GID)
          env:
            - name: DOCKER_GROUP_GID
              value: "123"
            - name: DOCKER_IPTABLES_LEGACY
              value: "1"
          securityContext:
            privileged: true
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /run/docker
            - name: dind-externals
              mountPath: /home/runner/externals
      volumes:
        - name: work
          emptyDir: {}
        - name: dind-sock
          emptyDir: {}
        - name: dind-externals
          emptyDir: {}
