apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: superset-postgresql
  namespace: startup-cdtn--superset-prod
spec:
  encryptedData:
    password: AgB8G63/gPFptZgWQurkwEd8pb+WLjtVzVZ2v/KIOEh4RALg6EoEfVnmtemhE8bKhXYxZ4qj9MbQ3DuRTMJK4yLsOsFLwVwF/onUrV20Ji/uxq8zXKuHsSQ9mqDk7bwbABmc6Fy0ysNaJFx7ozS96xUmyw5nvOZa4Vwe7dR1+4piiqzgRCYZigPBsNL6RWe4avurAKQgtib2mX+Zgu4wKC/iDRFLC7lNkynDaVktQRLk4wl6HwmcaWbqgjFKz6GqzOMQo6Ako5MoXgAS4OImMJ3AZhNrfMVV3CExpU1hOzIwr/tWjGgsRp0y8n8qgp71jjWjuiaSZPK3ClrC9oT8UVUN2Kbwd+SNbWkwgGnNmMap02bA5GSUG7P0CavtbLdKFRH3hom0OP1WIaoKLD8SvywsrmEwXk0qSfbrF6q2kaPfyFszHK2tWRTvm4VOF33MZBRA7ICTA5CA9vbuolYENPgcp7+hhR5vovDjJ0Ql76hzh3XWqKOq4dwQTzbGyM409ISH5M9sJ5r4IfQet5oLVMlrAGZAEeqtm/WzsWi5GXsgwJ9vtFqFgNRwY9rkGzWAyjsjNSo7kNMlNnSoq/+E9Ju35LZPU6/VONNKm13EloylByftMUas3rCnwLib97FNb6SuCNMsv2xZoXjtZPW+Myt9loucgAF2ZlDUPkEPyf1hYidpHJQhWy8LR6eb8QwEarb3FbOaIgiH4SuRsWfJiiswnP3HG+l5DBv8wIdIwWPHkQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: superset-postgresql
    type: Opaque
