metabase:
  enabled: true
  fullnameOverride: metabase
  cnpg-cluster:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 200m
        memory: 1Gi
    backup:
      enabled: true
      barmanObjectStore:
        destinationPath: s3://tumeplay-prod-backups/metabase-prod
        endpointURL: https://s3.gra.io.cloud.ovh.net
        s3Credentials:
          accessKeyId:
            name: &s3secretName tumeplay-prod-backups-access-key
          region:
            name: *s3secretName
          secretAccessKey:
            name: *s3secretName

metabase-matomo-sync:
  enabled: true
  fullnameOverride: metabase-matomo-sync
  cnpg-cluster:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 100m
        memory: 512Mi

metabase-matomo-sync-vitrine:
  enabled: true
  fullnameOverride: metabase-matomo-sync-vitrine
  secretName: matomo-sync-cronjob-vitrine
  # use db from metabase-matomo-sync
  pgdatabase:
    secretName: metabase-matomo-sync-app
  cnpg-cluster:
    enabled: false

