apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: huginn-secrets
  namespace: huginn
spec:
  encryptedData:
    APP_SECRET_TOKEN: AgB94jQlq+BESVgge8RHqmjygBpuP6Ma0vZP0Scm4OnAsy34SrtnSyg06h8zP+WYW1eHFSHptLtGbGqmwpeF5Q3Rk1puW9jwEvLHXRpjMZyYUnwC9vQP0HBndBX5Y8yqpZDIhYMxHnrJABatu1rv0DJI5/qSPC0TURElzQeZQnkdvXGDASvj6378ydekMV1Ct1yZ27olqG1A80OFfzxo4+Dfn5VUAV5oeQTLFfNrDjF9yN1fLU+AzoGuPj9PppUfIZ8M99d1aLN61sAhof1iN7ET+0lDBDvyxhiEuycvw3f0g3UwdtQKXLt7IbuAt/QlyjEx4HVOQ8aB+XMsLxHAhtEJ6Habho4Flr0t8gKiIev514KrNnz6LkNOyKBs6DXNGBVG3bZdAVC8XwIUezssOBaflMQNtHtdHWxECoczJng2yPsYcsF8smw5prnH9sgEe/mYRqGxr6TVE4fmuWNOTIbokF1R+KY1LFv6mmFUFCZTgc4SsmOijIxTVvuaTokUyjzZFS/qahw/UaSewW1qOqewIkE5FQkUOqmfV1IUhfkIUzW+UDTuJhR5/Mc7fpsekTiQ4KrJUgLk8dpLoeKqGakN/NO4NRrk+ovbPSeYO6j8gmm390RfhsWl4j3i7cmuS4dieLWnrC6w+ut6kG3bEplW8ovK+ODjxf/hxT6qRHA7ouVTxhRjufyNKH+vn58+eOArBouuG0qe1ED03iSBOXfh9KaGi/bHDAes/0a4Sfb/blknPmFtTjFWxHEagAqGLD/tRLulWyXgAeIHeUMZC4vKeEo70kEumq9x3El1XMjrXGao6yBb3UoVsAcgd9o8o26AwDR7IjM+EtNi/YtMoTMLafha0So2hd2f4DAmJp171w==
  template:
    metadata:
      name: huginn-secrets
      namespace: huginn
