metabase:
  host: metabase-1j1s.fabrique.social.gouv.fr
  ingress:
    annotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: true

final-appset:
  importSecretsFromStartup: true
  importSreSecretsList:
    - matomo-key

metabase-matomo-sync:
  matomoSiteId: 104

metabase-matomo-sync-back:
  matomoSiteId: 106
  destinationTable: matomo_back
