apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data
spec:
  storageClassName: {{ .Values.persistence.storage.className }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storage.size }}