apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-review
  namespace: fce-preprod
spec:
  policyTypes:
  - Ingress
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          application: fce
