---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pg-secret
spec:
  rules:
    - name: sync-secrets-superuser
      match:
        any:
          - resources:
              kinds:
                - Namespace
              annotations:
                field.cattle.io/projectId: "c-m-97jxtvnv:p-fklgj"
      generate:
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: pg-superuser
        clone:
          namespace: fce-preprod
          name: pg-superuser
    - name: sync-secrets-app
      match:
        any:
          - resources:
              kinds:
                - Namespace
              annotations:
                field.cattle.io/projectId: "c-m-97jxtvnv:p-fklgj"
      generate:
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: pg-app
        clone:
          namespace: fce-preprod
          name: pg-app

    - name: sync-secrets-n8n-superuser
      match:
        any:
          - resources:
              kinds:
                - Namespace
              annotations:
                field.cattle.io/projectId: "c-m-97jxtvnv:p-fklgj"
      generate:
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: pg-n8n-superuser
        clone:
          namespace: fce-preprod
          name: pg-n8n-superuser
    - name: sync-secrets-n8n-app
      match:
        any:
          - resources:
              kinds:
                - Namespace
              annotations:
                field.cattle.io/projectId: "c-m-97jxtvnv:p-fklgj"
      generate:
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: pg-n8n-app
        clone:
          namespace: fce-preprod
          name: pg-n8n-app

    - name: sync-secrets-strapi-superuser
      match:
        any:
          - resources:
              kinds:
                - Namespace
              annotations:
                field.cattle.io/projectId: "c-m-97jxtvnv:p-fklgj"
      generate:
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: pg-strapi-superuser
        clone:
          namespace: fce-preprod
          name: pg-strapi-superuser
    - name: sync-secrets-strapi-app
      match:
        any:
          - resources:
              kinds:
                - Namespace
              annotations:
                field.cattle.io/projectId: "c-m-97jxtvnv:p-fklgj"
      generate:
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: pg-strapi-app
        clone:
          namespace: fce-preprod
          name: pg-strapi-app
