cnpg-cluster:
  instances: 3
  fullnameOverride: pg
  postgresqlParameters:
    TimeZone: "Europe/Paris"
  monitoring:
    enablePodMonitor: true
  persistence:
    size: 10Gi
  image:
    repository: "ghcr.io/cloudnative-pg/postgresql"
    tag: "15.3"
  backup:
    enabled: true
    schedule: "0 0 0 * * *" # daily
    retentionPolicy: 30d
    barmanObjectStore:
      endpointURL: https://s3.gra.io.cloud.ovh.net
      destinationPath: s3://argocd-sre-cnpg-clusters/backups/bitwarden-ovh
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: bucket_access_key
        secretAccessKey:
          name: s3-creds
          key: bucket_secret_key
        region:
          name: s3-creds
          key: bucket_region
      wal:
        compression: gzip
      data:
        compression: gzip
  recovery:
    enabled: true
    barmanObjectStore:
      endpointURL: https://s3.gra.io.cloud.ovh.net
      destinationPath: s3://argocd-sre-cnpg-clusters/backups
      serverName: bitwarden
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: bucket_access_key
        secretAccessKey:
          name: s3-creds
          key: bucket_secret_key
        region:
          name: s3-creds
          key: bucket_region
      wal:
        compression: gzip
      data:
        compression: gzip
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 2Gi

vaultwarden:
  domain: https://bitwarden.fabrique.social.gouv.fr
  adminToken:
    existingSecret: "admin-creds"
    existingSecretKey: "token"
  database:
    type: postgresql
    existingSecret: "db-creds"
    existingSecretKey: "uri"
  signupsAllowed: false
  invitationsAllowed: true
  invitationOrgName: "Fabrique des ministères sociaux"
  data:
    name: "vaultwarden-data"
    size: "10Gi"
  ingress:
    enabled: true
    hostname: bitwarden.fabrique.social.gouv.fr
    tls: true
    tlsSecret: bitwarden-crt
    additionalAnnotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: letsencrypt-prod
  smtp:
    from: contact@diffusion.fabrique.social.gouv.fr
    host: smtp.tipimail.com
    port: 587
    security: starttls
    existingSecret: smtp-creds
    username:
      existingSecretKey: username
    password:
      existingSecretKey: password
  resources:
    limits:
      cpu: 300m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 256Mi
